Repository woowacourse-teams/2025-yagu-bogu, pull requests merged in 2025-10, with the labels that each got.

#575 fix: 프래그먼트 전환 Analytics 로깅시 이름 난독화 버그 수정
  android/app/src/main/java/com/yagubogu/presentation/MainActivity.kt
Labels: 🔨 fix, 🤖 AN

#645 Dev-be -> Dev
  backend/src/main/java/com/yagubogu/like/controller/LikeController.java
  backend/src/main/java/com/yagubogu/like/controller/LikeControllerInterface.java
  backend/src/main/java/com/yagubogu/like/dto/LikeBatchRequest.java
  backend/src/main/java/com/yagubogu/like/dto/TeamLikeCountResponse.java
  backend/src/main/java/com/yagubogu/like/repository/LikeRepository.java
  backend/src/main/java/com/yagubogu/like/service/LikeService.java
  backend/src/test/java/com/yagubogu/like/LikeE2eTest.java
Labels: 🐒 BE

#656 fix: 좋아요 응답 필드 수정 (null 비허용)
  backend/src/main/java/com/yagubogu/like/dto/TeamLikeCountResponse.java
  backend/src/main/java/com/yagubogu/like/repository/LikeRepository.java
  backend/src/test/java/com/yagubogu/like/LikeE2eTest.java
Labels: 🔨 fix, 🐒 BE

#659 fix: 좋아요 배치 Request 필드 teamId -> teamCode로 수정
  backend/src/main/java/com/yagubogu/like/dto/LikeBatchRequest.java
  backend/src/main/java/com/yagubogu/like/service/LikeService.java
  backend/src/test/java/com/yagubogu/like/LikeE2eTest.java
Labels: 🔨 fix, 🐒 BE
