Repository woowacourse-teams/2025-yagu-bogu, pull requests merged in 2025-09, with the labels that each got.

#479 refactor: 팀 도메인 프로퍼티 변경
  android/app/src/main/java/com/yagubogu/domain/model/Team.kt
  android/app/src/main/res/layout/fragment_favorite_team_confirm.xml
  android/app/src/main/res/layout/item_favorite_team.xml
  android/app/src/main/res/layout/item_livetalk_stadium.xml
Labels: 🤖 AN, 🔧 refactor

#484 design: BottomNavigation 아이콘 순서 변경 (홈, 현장톡, 통계, 직관내역 순)
  android/app/src/main/res/menu/menu_bottom_navigation.xml
Labels: 🤖 AN, 🎀 design

#487 refactor: 더보기/접기 UX 개선
  android/app/src/main/res/layout/fragment_home.xml
  android/app/src/main/res/layout/fragment_stats_detail.xml
Labels: 🤖 AN, 🔧 refactor

#503 feat: 뒤로가기 버튼 두 번 클릭 시 앱 종료
  android/app/src/main/java/com/yagubogu/presentation/MainActivity.kt
  android/app/src/main/res/values/strings.xml
Labels: 🚀 feat, 🤖 AN

#526 chore: Firebase Analytics 로깅 적용
  android/app/src/main/java/com/yagubogu/YaguBoguApplication.kt
  android/app/src/main/java/com/yagubogu/presentation/MainActivity.kt
  android/app/src/main/java/com/yagubogu/presentation/attendance/AttendanceHistoryFragment.kt
  android/app/src/main/java/com/yagubogu/presentation/attendance/AttendanceHistoryViewModel.kt
  android/app/src/main/java/com/yagubogu/presentation/home/HomeFragment.kt
  android/app/src/main/java/com/yagubogu/presentation/livetalk/chat/LivetalkChatActivity.kt
  android/app/src/main/java/com/yagubogu/presentation/livetalk/chat/LivetalkChatViewModel.kt
  android/app/src/main/java/com/yagubogu/presentation/login/LoginActivity.kt
  android/app/src/main/java/com/yagubogu/presentation/setting/SettingDeleteAccountFragment.kt
  android/app/src/main/res/layout/activity_livetalk_chat.xml
  android/app/src/main/res/layout/fragment_attendance_history.xml
  android/app/src/main/res/layout/fragment_setting_delete_account.xml
Labels: 🤖 AN, ⚙️ chore

#498 feat: 현장톡 UiState 추가 및 ShimmerLayout 적용
  android/app/build.gradle.kts
  android/app/src/main/java/com/yagubogu/presentation/livetalk/chat/LivetalkChatActivity.kt
  android/app/src/main/java/com/yagubogu/presentation/livetalk/chat/LivetalkChatViewModel.kt
  android/app/src/main/java/com/yagubogu/presentation/livetalk/chat/LivetalkUiState.kt
  android/app/src/main/java/com/yagubogu/presentation/util/BindingAdapters.kt
  android/app/src/main/res/layout/activity_livetalk_chat.xml
  android/app/src/main/res/values/strings.xml
  android/gradle/libs.versions.toml
Labels: 🚀 feat, 🤖 AN

#495 feat: 인증한 경기의 현장톡방을 가장 위에 표시
  android/app/src/main/java/com/yagubogu/presentation/livetalk/LivetalkFragment.kt
  android/app/src/main/java/com/yagubogu/presentation/livetalk/LivetalkViewModel.kt
Labels: 🚀 feat, 🤖 AN

#532 build: 야구보구 v1.0.1
  android/app/build.gradle.kts
  android/app/src/main/java/com/yagubogu/domain/model/Team.kt
  android/app/src/main/java/com/yagubogu/presentation/home/HomeFragment.kt
  android/app/src/main/java/com/yagubogu/presentation/livetalk/chat/LivetalkChatActivity.kt
  android/app/src/main/java/com/yagubogu/presentation/setting/SettingAccountFragment.kt
  android/app/src/main/java/com/yagubogu/presentation/setting/SettingDeleteAccountFragment.kt
  android/app/src/main/res/layout/fragment_favorite_team_confirm.xml
  android/app/src/main/res/layout/fragment_home.xml
  android/app/src/main/res/layout/fragment_stats_detail.xml
  android/app/src/main/res/layout/item_favorite_team.xml
  android/app/src/main/res/layout/item_livetalk_stadium.xml
  android/app/src/main/res/menu/menu_bottom_navigation.xml
  android/app/src/main/res/values/strings.xml
Labels: 🤖 AN, 🔫 deploy

#535 dev-be -> dev
  backend/.gitignore
Labels: 🐒 BE

#511 feat: 닉네임 중복 검증, 회원가입시 UUID 닉네임으로 가입, 승리요정 랭킹 탈퇴한 회원 조회 불가
  backend/src/main/java/com/yagubogu/auth/dto/AuthResponse.java
  backend/src/main/java/com/yagubogu/auth/dto/GoogleAuthResponse.java
  backend/src/main/java/com/yagubogu/auth/dto/LoginResponse.java
  backend/src/main/java/com/yagubogu/auth/gateway/LocalAuthGateway.java
  backend/src/main/java/com/yagubogu/auth/service/AuthService.java
  backend/src/main/java/com/yagubogu/checkin/dto/VictoryFairyRankingEntryResponse.java
  backend/src/main/java/com/yagubogu/checkin/repository/CheckInRepository.java
  backend/src/main/java/com/yagubogu/global/GlobalExceptionHandler.java
  backend/src/main/java/com/yagubogu/global/exception/ConflictException.java
  backend/src/main/java/com/yagubogu/member/domain/Member.java
  backend/src/main/java/com/yagubogu/member/domain/Nickname.java
  backend/src/main/java/com/yagubogu/member/dto/MemberInfoResponse.java
  backend/src/main/java/com/yagubogu/member/dto/MemberNicknameResponse.java
  backend/src/main/java/com/yagubogu/member/repository/MemberRepository.java
  backend/src/main/java/com/yagubogu/member/service/MemberService.java
  backend/src/main/java/com/yagubogu/talk/dto/TalkResponse.java
  backend/src/test/java/com/yagubogu/auth/AuthE2eTest.java
  backend/src/test/java/com/yagubogu/auth/gateway/FakeAuthGateway.java
  backend/src/test/java/com/yagubogu/auth/service/AuthServiceTest.java
  backend/src/test/java/com/yagubogu/checkin/service/CheckInServiceTest.java
  backend/src/test/java/com/yagubogu/member/MemberE2eTest.java
  backend/src/test/java/com/yagubogu/member/domain/MemberTest.java
  backend/src/test/java/com/yagubogu/member/service/MemberServiceTest.java
  backend/src/test/java/com/yagubogu/support/TestFixture.java
  backend/src/test/java/com/yagubogu/support/member/MemberBuilder.java
Labels: 🚀 feat, 🐒 BE

#505 design: 용어 설명 Tooltip 추가
  android/app/build.gradle.kts
  android/app/src/main/java/com/yagubogu/presentation/home/HomeFragment.kt
  android/app/src/main/java/com/yagubogu/presentation/stats/detail/BarChartManager.kt
  android/app/src/main/java/com/yagubogu/presentation/stats/my/StatsMyFragment.kt
  android/app/src/main/java/com/yagubogu/presentation/util/UiExt.kt
  android/app/src/main/res/drawable/ic_info.xml
  android/app/src/main/res/layout/fragment_home.xml
  android/app/src/main/res/layout/fragment_stats_my.xml
  android/app/src/main/res/values/strings.xml
  android/gradle/libs.versions.toml
Labels: 🤖 AN, 🎀 design

#513 feat: 내 팀 최근 10 경기 인증 승률 조회 기능 구현
  backend/build.gradle
  backend/src/main/java/com/yagubogu/checkin/repository/CheckInRepository.java
  backend/src/main/java/com/yagubogu/checkin/repository/CustomCheckInRepository.java
  backend/src/main/java/com/yagubogu/checkin/repository/CustomCheckInRepositoryImpl.java
  backend/src/main/java/com/yagubogu/global/config/QueryDslConfig.java
  backend/src/main/java/com/yagubogu/stat/controller/StatController.java
  backend/src/main/java/com/yagubogu/stat/controller/StatControllerInterface.java
  backend/src/main/java/com/yagubogu/stat/dto/RecentGamesWinRateResponse.java
  backend/src/main/java/com/yagubogu/stat/service/StatService.java
  backend/src/main/resources/application-local.yml
  backend/src/test/java/com/yagubogu/auth/config/AuthTestConfig.java
  backend/src/test/java/com/yagubogu/game/service/GameServiceTest.java
  backend/src/test/java/com/yagubogu/stadium/service/StadiumServiceTest.java
  backend/src/test/java/com/yagubogu/stat/service/StatServiceTest.java
  backend/src/test/java/com/yagubogu/talk/service/TalkReportServiceTest.java
  backend/src/test/java/com/yagubogu/talk/service/TalkServiceTest.java
Labels: 🚀 feat, 🐒 BE

#517 feat: 좋아요 배치 처리 기능 추가
  backend/src/main/java/com/yagubogu/like/controller/LikeController.java
  backend/src/main/java/com/yagubogu/like/domain/Like.java
  backend/src/main/java/com/yagubogu/like/dto/LikeBatchRequest.java
  backend/src/main/java/com/yagubogu/like/dto/LikeCountsResponse.java
  backend/src/main/java/com/yagubogu/like/dto/TeamLikeCountResponse.java
  backend/src/main/java/com/yagubogu/like/repository/LikeRepository.java
  backend/src/main/java/com/yagubogu/like/repository/LikeWindowRepository.java
  backend/src/main/java/com/yagubogu/like/service/LikeService.java
  backend/src/main/resources/db/migration/mysql/V2__add_like_counts_to_games.sql
  backend/src/test/java/com/yagubogu/like/LikeE2eTest.java
  backend/src/test/java/com/yagubogu/support/E2eTestBase.java
Labels: 🚀 feat, 🐒 BE

#531 feat: 구장별 팬 비율 SSE 기술 도입
  backend/src/main/java/com/yagubogu/checkin/dto/FanRateByGameResponse.java
  backend/src/main/java/com/yagubogu/checkin/service/CheckInService.java
  backend/src/main/java/com/yagubogu/global/config/SseConfig.java
  backend/src/main/java/com/yagubogu/global/config/SseHeartbeatProperties.java
  backend/src/main/java/com/yagubogu/sse/SseEventHandler.java
  backend/src/main/java/com/yagubogu/sse/controller/StreamController.java
  backend/src/main/java/com/yagubogu/sse/dto/CheckInCreatedEvent.java
  backend/src/main/java/com/yagubogu/sse/dto/GameWithFanRateResponse.java
  backend/src/main/java/com/yagubogu/sse/repository/SseEmitterRegistry.java
  backend/src/main/java/com/yagubogu/sse/service/SseEmitterService.java
  backend/src/main/java/com/yagubogu/sse/service/SseHeartbeatScheduler.java
  backend/src/main/resources/application.yml
  backend/src/test/java/com/yagubogu/checkin/service/CheckInServiceTest.java
  backend/src/test/java/com/yagubogu/sse/SseEventHandlerTest.java
  backend/src/test/java/com/yagubogu/sse/service/SseEmitterServiceTest.java
  backend/src/test/resources/application.yml
  backend/src/test/resources/log4j2-spring.xml
Labels: 🚀 feat, 🐒 BE

#518 feat: 승리요정 랭킹 베이즈 정리로 구현, 팀 별 필터링 추가
  backend/.gitignore
  backend/build.gradle
  backend/src/main/java/com/yagubogu/checkin/controller/CheckInController.java
  backend/src/main/java/com/yagubogu/checkin/controller/CheckInControllerInterface.java
  backend/src/main/java/com/yagubogu/checkin/dto/TeamFilter.java
  backend/src/main/java/com/yagubogu/checkin/dto/VictoryFairyRank.java
  backend/src/main/java/com/yagubogu/checkin/dto/VictoryFairyRankingEntryResponse.java
  backend/src/main/java/com/yagubogu/checkin/dto/VictoryFairyRankingResponses.java
  backend/src/main/java/com/yagubogu/checkin/repository/CheckInRepository.java
  backend/src/main/java/com/yagubogu/checkin/repository/CustomCheckInRepository.java
  backend/src/main/java/com/yagubogu/checkin/repository/CustomCheckInRepositoryImpl.java
  backend/src/main/java/com/yagubogu/checkin/service/CheckInService.java
  backend/src/main/java/com/yagubogu/global/config/QueryDslConfig.java
  backend/src/main/resources/application-dev.yml
  backend/src/main/resources/application-local.yml
  backend/src/main/resources/application-prod.yml
  backend/src/main/resources/application.yml
  backend/src/test/java/com/yagubogu/auth/AuthE2eTest.java
  backend/src/test/java/com/yagubogu/checkin/CheckInE2eTest.java
  backend/src/test/java/com/yagubogu/checkin/service/CheckInServiceTest.java
  backend/src/test/java/com/yagubogu/talk/service/TalkServiceTest.java
Labels: 🚀 feat, 🐒 BE

#543 design: 오늘의 팬 현황 'VS' 텍스트 애니메이션 추가
  android/app/src/main/java/com/yagubogu/presentation/home/stadium/StadiumFanRateViewHolder.kt
Labels: 🤖 AN, 🎀 design

#554 fix: 충돌 해결
  android/app/build.gradle.kts
  android/app/src/main/java/com/yagubogu/YaguBoguApplication.kt
  android/app/src/main/java/com/yagubogu/presentation/MainActivity.kt
  android/app/src/main/java/com/yagubogu/presentation/attendance/AttendanceHistoryFragment.kt
  android/app/src/main/java/com/yagubogu/presentation/attendance/AttendanceHistoryViewModel.kt
  android/app/src/main/java/com/yagubogu/presentation/dialog/DefaultDialogFragment.kt
  android/app/src/main/java/com/yagubogu/presentation/favorite/FavoriteTeamConfirmFragment.kt
  android/app/src/main/java/com/yagubogu/presentation/home/HomeFragment.kt
  android/app/src/main/java/com/yagubogu/presentation/home/HomeViewModel.kt
  android/app/src/main/java/com/yagubogu/presentation/home/stadium/StadiumFanRateViewHolder.kt
  android/app/src/main/java/com/yagubogu/presentation/livetalk/LivetalkFragment.kt
  android/app/src/main/java/com/yagubogu/presentation/livetalk/LivetalkViewModel.kt
  android/app/src/main/java/com/yagubogu/presentation/livetalk/chat/LivetalkChatActivity.kt
  android/app/src/main/java/com/yagubogu/presentation/livetalk/chat/LivetalkChatViewModel.kt
  android/app/src/main/java/com/yagubogu/presentation/livetalk/chat/LivetalkUiState.kt
  android/app/src/main/java/com/yagubogu/presentation/login/InAppUpdateType.kt
  android/app/src/main/java/com/yagubogu/presentation/login/LoginActivity.kt
  android/app/src/main/java/com/yagubogu/presentation/login/VersionInfo.kt
  android/app/src/main/java/com/yagubogu/presentation/setting/SettingDeleteAccountFragment.kt
  android/app/src/main/java/com/yagubogu/presentation/setting/SettingNicknameEditFragment.kt
  android/app/src/main/java/com/yagubogu/presentation/stats/StatsFragment.kt
  android/app/src/main/java/com/yagubogu/presentation/stats/detail/BarChartManager.kt
  android/app/src/main/java/com/yagubogu/presentation/stats/detail/StatsDetailFragment.kt
  android/app/src/main/java/com/yagubogu/presentation/stats/my/StatsMyFragment.kt
  android/app/src/main/java/com/yagubogu/presentation/util/BindingAdapters.kt
  android/app/src/main/java/com/yagubogu/presentation/util/ScrollToTop.kt
  android/app/src/main/java/com/yagubogu/presentation/util/UiExt.kt
  android/app/src/main/res/drawable/ic_info.xml
  android/app/src/main/res/layout/activity_livetalk_chat.xml
  android/app/src/main/res/layout/fragment_attendance_history.xml
  android/app/src/main/res/layout/fragment_home.xml
  android/app/src/main/res/layout/fragment_setting_delete_account.xml
  android/app/src/main/res/layout/fragment_stats_detail.xml
  android/app/src/main/res/layout/fragment_stats_my.xml
  android/app/src/main/res/values/strings.xml
  android/gradle/libs.versions.toml
Labels: 🔨 fix, 🐒 BE

#557 feat: memberId로 칼럼명 수정
  backend/src/main/java/com/yagubogu/like/dto/LikeBatchRequest.java
  backend/src/main/java/com/yagubogu/like/repository/LikeWindowRepository.java
  backend/src/main/java/com/yagubogu/like/service/LikeService.java
  backend/src/main/resources/db/migration/mysql/V3__rename_user_column.sql
  backend/src/test/java/com/yagubogu/like/LikeE2eTest.java
Labels: 🚀 feat, 🐒 BE

#561 fix: 승리 요정 조회 시 내 랭킹이 0으로 나오는 문제 수정
  backend/src/main/java/com/yagubogu/checkin/repository/CustomCheckInRepositoryImpl.java
  backend/src/main/java/com/yagubogu/checkin/service/CheckInService.java
  backend/src/test/java/com/yagubogu/checkin/service/CheckInServiceTest.java
Labels: 🔨 fix, 🐒 BE

#565 fix: api 응답 추가된 것 삭제
  backend/src/main/java/com/yagubogu/checkin/dto/FanRateByGameResponse.java
  backend/src/main/java/com/yagubogu/checkin/dto/VictoryFairyRankingResponses.java
  backend/src/test/java/com/yagubogu/checkin/CheckInE2eTest.java
Labels: 🔨 fix, 🐒 BE

#572 fix: year 수정
  backend/src/main/java/com/yagubogu/checkin/controller/CheckInController.java
  backend/src/main/java/com/yagubogu/checkin/controller/CheckInControllerInterface.java
  backend/src/main/java/com/yagubogu/checkin/service/CheckInService.java
Labels: 🔨 fix, 🐒 BE

#573 fix: year 수정 (#572)
  backend/src/main/java/com/yagubogu/checkin/controller/CheckInController.java
  backend/src/main/java/com/yagubogu/checkin/controller/CheckInControllerInterface.java
  backend/src/main/java/com/yagubogu/checkin/service/CheckInService.java
Labels: 🐒 BE

#578 fix: 승리 요정 승률 계산 버그, 직관 내역 조회 버그 수정
  backend/src/main/java/com/yagubogu/checkin/repository/CustomCheckInRepositoryImpl.java
  backend/src/main/java/com/yagubogu/checkin/service/CheckInService.java
  backend/src/test/java/com/yagubogu/checkin/service/CheckInServiceTest.java
Labels: 🔨 fix, 🐒 BE

#581 feat: 직관 내역 기준 수정
  backend/src/main/java/com/yagubogu/checkin/repository/CustomCheckInRepositoryImpl.java
Labels: 🚀 feat, 🐒 BE

#592 feat: 배지 화면 UI 구현
  android/.editorconfig
  android/app/build.gradle.kts
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/yagubogu/presentation/MainActivity.kt
  android/app/src/main/java/com/yagubogu/presentation/theme/Type.kt
  android/app/src/main/java/com/yagubogu/ui/badge/BadgeActivity.kt
  android/app/src/main/java/com/yagubogu/ui/badge/component/Badge.kt
  android/app/src/main/java/com/yagubogu/ui/badge/component/BadgeBottomSheet.kt
  android/app/src/main/java/com/yagubogu/ui/badge/component/BadgeScreen.kt
  android/app/src/main/java/com/yagubogu/ui/badge/component/BadgeToolbar.kt
  android/app/src/main/java/com/yagubogu/ui/badge/component/EmptyBadge.kt
  android/app/src/main/java/com/yagubogu/ui/badge/component/MainBadgeCard.kt
  android/app/src/main/java/com/yagubogu/ui/badge/model/BadgeFixture.kt
  android/app/src/main/java/com/yagubogu/ui/badge/model/BadgeUiModel.kt
  android/app/src/main/java/com/yagubogu/ui/theme/Color.kt
  android/app/src/main/java/com/yagubogu/ui/theme/Font.kt
  android/app/src/main/java/com/yagubogu/ui/theme/Theme.kt
  android/app/src/main/java/com/yagubogu/ui/theme/Type.kt
  android/app/src/main/java/com/yagubogu/ui/util/ModifierExt.kt
  android/app/src/main/res/drawable/ic_trophy.xml
  android/app/src/main/res/drawable/img_badge_lock.png
  android/app/src/main/res/layout/activity_main.xml
  android/app/src/main/res/values/strings.xml
  android/gradle/libs.versions.toml
Labels: 🚀 feat, 🤖 AN

#610 refactor: 승/무/패 집계 쿼리를 하나로 통합
  backend/src/main/java/com/yagubogu/checkin/dto/StatCounts.java
  backend/src/main/java/com/yagubogu/checkin/repository/CustomCheckInRepository.java
  backend/src/main/java/com/yagubogu/checkin/repository/CustomCheckInRepositoryImpl.java
  backend/src/main/java/com/yagubogu/stat/service/StatService.java
Labels: 🐒 BE, 🔧 refactor

#611 chore: hikcari Pool 모니터링을 위한 micrometer, prometheus endpoint 추가
  backend/build.gradle
  backend/src/main/resources/application-prod.yml
  backend/src/main/resources/application.yml
Labels: 🐒 BE, ⚙️ chore

#619 fix: 승리요정 랭킹 중 인증 안 한 사람 제외
  backend/src/main/java/com/yagubogu/checkin/dto/VictoryFairyRankingResponses.java
  backend/src/main/java/com/yagubogu/checkin/repository/CustomCheckInRepositoryImpl.java
  backend/src/main/java/com/yagubogu/checkin/service/CheckInService.java
  backend/src/test/java/com/yagubogu/checkin/CheckInE2eTest.java
  backend/src/test/java/com/yagubogu/checkin/service/CheckInServiceTest.java
Labels: 🔨 fix, 🐒 BE

#626 feat: sse 로깅 추가
  backend/src/main/java/com/yagubogu/sse/repository/SseEmitterRegistry.java
Labels: 🚀 feat, 🐒 BE
