Repository woowacourse-teams/2025-yagu-bogu, pull requests merged in 2025-08, with the labels that each got.

#142 feat: team에 TeamCode 컬럼 추가
  backend/src/main/java/com/yagubogu/team/domain/Team.java
  backend/src/main/resources/data.sql
  backend/src/test/java/com/yagubogu/member/domain/MemberTest.java
  backend/src/test/resources/test-data.sql
Labels: 🚀 feat, 🐒 BE

#139 feat: 야구 경기 일정 크롤링 및 저장 기능 구현
  backend/build.gradle
  backend/src/main/java/com/yagubogu/game/domain/Game.java
  backend/src/main/java/com/yagubogu/game/dto/KboClientResponse.java
  backend/src/main/java/com/yagubogu/game/dto/KboGameResponse.java
  backend/src/main/java/com/yagubogu/game/schedule/GameScheduler.java
  backend/src/main/java/com/yagubogu/game/service/GameService.java
  backend/src/main/java/com/yagubogu/game/service/client/KboClient.java
  backend/src/main/java/com/yagubogu/global/config/KboClientConfig.java
  backend/src/main/java/com/yagubogu/global/config/KboClientProperties.java
  backend/src/main/java/com/yagubogu/global/config/ScheduleConfig.java
  backend/src/main/java/com/yagubogu/global/exception/ClientException.java
  backend/src/main/java/com/yagubogu/global/exception/YaguBoguException.java
  backend/src/main/java/com/yagubogu/stadium/repository/StadiumRepository.java
  backend/src/main/java/com/yagubogu/team/repository/TeamRepository.java
  backend/src/main/resources/application.yml
  backend/src/main/resources/data.sql
  backend/src/test/java/com/yagubogu/game/service/GameServiceTest.java
  backend/src/test/resources/application.yml
  backend/src/test/resources/test-data.sql
Labels: 🚀 feat, 🐒 BE

#145 feat: 홈 화면 구장 팬 현황 및 승리요정 랭킹 UI 구현
  android/app/src/main/java/com/yagubogu/data/dto/response/TeamOccupancyRateDto.kt
  android/app/src/main/java/com/yagubogu/data/dto/response/TeamOccupancyRatesResponse.kt
  android/app/src/main/java/com/yagubogu/data/repository/StatsDefaultRepository.kt
  android/app/src/main/java/com/yagubogu/domain/repository/StatsRepository.kt
  android/app/src/main/java/com/yagubogu/presentation/MainActivity.kt
  android/app/src/main/java/com/yagubogu/presentation/home/HomeFragment.kt
  android/app/src/main/java/com/yagubogu/presentation/home/HomeViewModel.kt
  android/app/src/main/java/com/yagubogu/presentation/home/model/Stadium.kt
  android/app/src/main/java/com/yagubogu/presentation/home/model/StadiumStatsUiModel.kt
  android/app/src/main/java/com/yagubogu/presentation/home/model/TeamOccupancyRate.kt
  android/app/src/main/java/com/yagubogu/presentation/home/model/TeamOccupancyRates.kt
  android/app/src/main/java/com/yagubogu/presentation/home/ranking/VictoryFairyAdapter.kt
  android/app/src/main/java/com/yagubogu/presentation/home/ranking/VictoryFairyItem.kt
  android/app/src/main/java/com/yagubogu/presentation/home/ranking/VictoryFairyViewHolder.kt
  android/app/src/main/java/com/yagubogu/presentation/livetalk/LiveTalkFragment.kt
  android/app/src/main/java/com/yagubogu/presentation/stats/StatsFragment.kt
  android/app/src/main/java/com/yagubogu/presentation/stats/StatsTab.kt
  android/app/src/main/java/com/yagubogu/presentation/stats/attendance/AttendanceHistoryFragment.kt
  android/app/src/main/java/com/yagubogu/presentation/stats/my/MyStatsFragment.kt
  android/app/src/main/java/com/yagubogu/presentation/stats/stadium/StadiumStatsFragment.kt
  android/app/src/main/java/com/yagubogu/presentation/stats/stadium/StadiumStatsViewModel.kt
  android/app/src/main/java/com/yagubogu/presentation/stats/stadium/StadiumStatsViewModelFactory.kt
  android/app/src/main/java/com/yagubogu/presentation/stats/stadium/model/StadiumStatsUiModel.kt
  android/app/src/main/java/com/yagubogu/presentation/stats/stadium/model/TeamOccupancyRate.kt
  android/app/src/main/java/com/yagubogu/presentation/stats/stadium/model/TeamOccupancyRates.kt
  android/app/src/main/java/com/yagubogu/presentation/stats/stadium/model/TeamOccupancyStatus.kt
  android/app/src/main/java/com/yagubogu/presentation/util/BindingAdapters.kt
  android/app/src/main/res/drawable/bg_stroke_gray300_radius_12dp.xml
  android/app/src/main/res/drawable/ic_arrow_down.xml
  android/app/src/main/res/drawable/ic_arrow_up.xml
  android/app/src/main/res/drawable/ic_livetalk.xml
  android/app/src/main/res/drawable/ic_medal_first.xml
  android/app/src/main/res/drawable/ic_medal_second.xml
  android/app/src/main/res/drawable/ic_medal_third.xml
  android/app/src/main/res/drawable/ic_record.xml
  android/app/src/main/res/drawable/ic_refresh.xml
  android/app/src/main/res/layout/activity_main.xml
  android/app/src/main/res/layout/fragment_attendance_history.xml
  android/app/src/main/res/layout/fragment_home.xml
  android/app/src/main/res/layout/fragment_live_talk.xml
  android/app/src/main/res/layout/fragment_my_stats.xml
  android/app/src/main/res/layout/fragment_stadium_stats.xml
  android/app/src/main/res/layout/item_stadium_chart_bar.xml
  android/app/src/main/res/layout/item_victory_fairy.xml
  android/app/src/main/res/menu/menu_bottom_navigation.xml
  android/app/src/main/res/values/colors.xml
  android/app/src/main/res/values/strings.xml
  android/app/src/main/res/values/styles.xml
Labels: 🚀 feat, 🤖 AN

#157 feat: 회원가입/로그인 기능 구현
  .github/workflows/backend-dev.yml
  backend/build.gradle
  backend/src/main/java/com/yagubogu/auth/client/AuthGateway.java
  backend/src/main/java/com/yagubogu/auth/client/GoogleAuthGateway.java
  backend/src/main/java/com/yagubogu/auth/config/GoogleAuthClientConfig.java
  backend/src/main/java/com/yagubogu/auth/config/GoogleAuthProperties.java
  backend/src/main/java/com/yagubogu/auth/config/JwtProperties.java
  backend/src/main/java/com/yagubogu/auth/controller/AuthController.java
  backend/src/main/java/com/yagubogu/auth/dto/AuthResponse.java
  backend/src/main/java/com/yagubogu/auth/dto/GoogleAuthResponse.java
  backend/src/main/java/com/yagubogu/auth/dto/GoogleErrorResponse.java
  backend/src/main/java/com/yagubogu/auth/dto/LoginRequest.java
  backend/src/main/java/com/yagubogu/auth/dto/LoginResponse.java
  backend/src/main/java/com/yagubogu/auth/dto/MemberClaims.java
  backend/src/main/java/com/yagubogu/auth/exception/GoogleAuthExceptionHandler.java
  backend/src/main/java/com/yagubogu/auth/exception/InvalidTokenException.java
  backend/src/main/java/com/yagubogu/auth/service/AuthService.java
  backend/src/main/java/com/yagubogu/auth/service/AuthValidator.java
  backend/src/main/java/com/yagubogu/auth/service/GoogleAuthValidator.java
  backend/src/main/java/com/yagubogu/auth/token/JwtProvider.java
  backend/src/main/java/com/yagubogu/global/GlobalExceptionHandler.java
  backend/src/main/java/com/yagubogu/global/exception/BadGatewayException.java
  backend/src/main/java/com/yagubogu/global/exception/UnAuthorizedException.java
  backend/src/main/java/com/yagubogu/member/domain/Member.java
  backend/src/main/java/com/yagubogu/member/domain/OAuthProvider.java
  backend/src/main/java/com/yagubogu/member/repository/MemberRepository.java
  backend/src/main/resources/application.yml
  backend/src/main/resources/data.sql
  backend/src/test/java/com/yagubogu/auth/AuthGatewayTest.java
  backend/src/test/java/com/yagubogu/auth/service/AuthServiceTest.java
  backend/src/test/java/com/yagubogu/auth/token/JwtProviderTest.java
  backend/src/test/java/com/yagubogu/global/config/TestConfig.java
  backend/src/test/java/com/yagubogu/member/domain/MemberTest.java
  backend/src/test/resources/application.yml
  backend/src/test/resources/test-data.sql
Labels: 🚀 feat, 🐒 BE

#161 design: 내 통계 화면 UI 구현
  android/app/src/main/res/layout/fragment_home.xml
  android/app/src/main/res/layout/fragment_my_stats.xml
  android/app/src/main/res/values/strings.xml
Labels: 🤖 AN, 🎀 design

#151 design: 현장톡 구장 선택 아이템 레이아웃 구현
  android/app/src/main/res/drawable/bg_white_stroke_gray100_radius_12dp.xml
  android/app/src/main/res/drawable/bg_white_stroke_primary500_radius_12dp.xml
  android/app/src/main/res/drawable/ic_arrow_right.xml
  android/app/src/main/res/drawable/ic_users.xml
  android/app/src/main/res/layout/item_livetalk_stadium.xml
  android/app/src/main/res/layout/item_stadium_chart_bar.xml
  android/app/src/main/res/values/strings.xml
  android/app/src/main/res/values/styles.xml
Labels: 🤖 AN, 🎀 design

#156 feat: 인증 여부 조회 기능 구현
  backend/src/main/java/com/yagubogu/checkin/controller/CheckInController.java
  backend/src/main/java/com/yagubogu/checkin/dto/CheckInStatusResponse.java
  backend/src/main/java/com/yagubogu/checkin/repository/CheckInRepository.java
  backend/src/main/java/com/yagubogu/checkin/service/CheckInService.java
  backend/src/test/java/com/yagubogu/checkin/CheckInIntegrationTest.java
  backend/src/test/java/com/yagubogu/checkin/service/CheckInServiceTest.java
Labels: 🚀 feat, 🐒 BE

#183 feat: token 재발급 기능 구현
  .github/workflows/backend-dev.yml
  backend/src/main/java/com/yagubogu/auth/config/AuthTokenProperties.java
  backend/src/main/java/com/yagubogu/auth/controller/AuthController.java
  backend/src/main/java/com/yagubogu/auth/domain/RefreshToken.java
  backend/src/main/java/com/yagubogu/auth/dto/TokenRequest.java
  backend/src/main/java/com/yagubogu/auth/dto/TokenResponse.java
  backend/src/main/java/com/yagubogu/auth/repository/RefreshTokenRepository.java
  backend/src/main/java/com/yagubogu/auth/service/AuthService.java
  backend/src/main/java/com/yagubogu/auth/support/AuthTokenProvider.java
  backend/src/main/java/com/yagubogu/global/GlobalExceptionHandler.java
  backend/src/main/resources/application.yml
  backend/src/test/java/com/yagubogu/auth/AuthIntegrationTest.java
  backend/src/test/java/com/yagubogu/auth/config/AuthTestConfig.java
  backend/src/test/java/com/yagubogu/auth/service/AuthServiceTest.java
  backend/src/test/java/com/yagubogu/auth/support/AuthTokenProviderTest.java
  backend/src/test/java/com/yagubogu/fixture/TestFixture.java
  backend/src/test/java/com/yagubogu/fixture/TestSupport.java
  backend/src/test/java/com/yagubogu/game/service/GameServiceTest.java
  backend/src/test/java/com/yagubogu/member/service/MemberServiceTest.java
  backend/src/test/resources/application.yml
Labels: 🚀 feat, 🐒 BE

#192 feat: 모니터링 환경 구축
  .github/workflows/android-ci.yml
  android/.gitignore
  android/app/build.gradle.kts
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/yagubogu/YaguBoguApplication.kt
  android/app/src/main/java/com/yagubogu/common/YaguBoguDebugTree.kt
  android/app/src/main/java/com/yagubogu/common/YaguBoguReleaseTree.kt
  android/app/src/main/java/com/yagubogu/presentation/home/HomeViewModel.kt
  android/app/src/main/java/com/yagubogu/presentation/login/LoginActivity.kt
  android/app/src/main/java/com/yagubogu/presentation/stats/my/MyStatsViewModel.kt
  android/build.gradle.kts
  android/gradle/libs.versions.toml
Labels: 🚀 feat, 🤖 AN

#132 feat: 구글 로그인 구현
  android/app/build.gradle.kts
  android/app/src/main/java/com/yagubogu/data/auth/GoogleCredentialManager.kt
  android/app/src/main/java/com/yagubogu/data/auth/GoogleCredentialResult.kt
  android/app/src/main/java/com/yagubogu/data/repository/AuthDefaultRepository.kt
  android/app/src/main/java/com/yagubogu/domain/model/LoginResult.kt
  android/app/src/main/java/com/yagubogu/domain/repository/AuthRepository.kt
  android/app/src/main/java/com/yagubogu/presentation/login/LoginActivity.kt
  android/app/src/main/java/com/yagubogu/presentation/login/LoginViewModel.kt
  android/app/src/main/java/com/yagubogu/presentation/login/LoginViewModelFactory.kt
  android/app/src/main/res/layout/activity_login.xml
  android/app/src/main/res/values/strings.xml
  android/gradle/libs.versions.toml
Labels: 🚀 feat, 🤖 AN

#187 feat: 현장톡 구장 목록 구현
  android/app/src/main/java/com/yagubogu/domain/model/Team.kt
  android/app/src/main/java/com/yagubogu/presentation/MainActivity.kt
  android/app/src/main/java/com/yagubogu/presentation/livetalk/LiveTalkFragment.kt
  android/app/src/main/java/com/yagubogu/presentation/livetalk/LivetalkFragment.kt
  android/app/src/main/java/com/yagubogu/presentation/livetalk/stadium/LivetalkStadiumAdapter.kt
  android/app/src/main/java/com/yagubogu/presentation/livetalk/stadium/LivetalkStadiumItem.kt
  android/app/src/main/java/com/yagubogu/presentation/livetalk/stadium/LivetalkStadiumViewHolder.kt
  android/app/src/main/java/com/yagubogu/presentation/util/TeamExt.kt
  android/app/src/main/res/layout/fragment_live_talk.xml
  android/app/src/main/res/layout/fragment_livetalk.xml
  android/app/src/main/res/layout/item_livetalk_stadium.xml
Labels: 🚀 feat, 🤖 AN

#193 refactor: Team 도메인 상태 변경
  android/app/src/main/java/com/yagubogu/data/dto/response/TeamOccupancyRateDto.kt
  android/app/src/main/java/com/yagubogu/domain/model/Team.kt
  android/app/src/main/java/com/yagubogu/presentation/favorite/FavoriteTeamUiModel.kt
  android/app/src/main/java/com/yagubogu/presentation/home/HomeFragment.kt
  android/app/src/main/java/com/yagubogu/presentation/home/model/TeamOccupancyRate.kt
  android/app/src/main/java/com/yagubogu/presentation/home/ranking/VictoryFairyItem.kt
  android/app/src/main/java/com/yagubogu/presentation/livetalk/LivetalkFragment.kt
  android/app/src/main/java/com/yagubogu/presentation/stats/attendance/AttendanceHistoryFragment.kt
  android/app/src/main/java/com/yagubogu/presentation/util/TeamExt.kt
  android/app/src/main/res/layout/item_livetalk_stadium.xml
  android/app/src/main/res/layout/item_victory_fairy.xml
Labels: 🤖 AN, 🔧 refactor

#182 feat: 야구 결과 크롤링 및 저장 기능 구현
  backend/src/main/java/com/yagubogu/game/domain/Game.java
  backend/src/main/java/com/yagubogu/game/domain/GameState.java
  backend/src/main/java/com/yagubogu/game/domain/ScoreBoard.java
  backend/src/main/java/com/yagubogu/game/dto/KboGameResponse.java
  backend/src/main/java/com/yagubogu/game/dto/KboGameResultResponse.java
  backend/src/main/java/com/yagubogu/game/dto/KboGamesResponse.java
  backend/src/main/java/com/yagubogu/game/exception/GameSyncException.java
  backend/src/main/java/com/yagubogu/game/exception/KboClientExceptionHandler.java
  backend/src/main/java/com/yagubogu/game/repository/GameRepository.java
  backend/src/main/java/com/yagubogu/game/schedule/GameScheduler.java
  backend/src/main/java/com/yagubogu/game/service/GameResultSyncService.java
  backend/src/main/java/com/yagubogu/game/service/GameScheduleSyncService.java
  backend/src/main/java/com/yagubogu/game/service/GameService.java
  backend/src/main/java/com/yagubogu/game/service/client/KboClient.java
  backend/src/main/java/com/yagubogu/game/service/client/KboGameResultClient.java
  backend/src/main/java/com/yagubogu/game/service/client/KboGameSyncClient.java
  backend/src/main/java/com/yagubogu/global/exception/ClientException.java
  backend/src/main/java/com/yagubogu/team/repository/TeamRepository.java
  backend/src/main/resources/application.yml
  backend/src/main/resources/data.sql
  backend/src/test/java/com/yagubogu/checkin/service/CheckInServiceTest.java
  backend/src/test/java/com/yagubogu/fixture/TestFixture.java
  backend/src/test/java/com/yagubogu/game/service/GameScheduleSyncServiceTest.java
  backend/src/test/java/com/yagubogu/game/service/GameServiceTest.java
  backend/src/test/resources/application.yml
  backend/src/test/resources/test-data.sql
Labels: 🚀 feat, 🐒 BE

#205 design: 로그인 버튼 클릭 효과 추가
  android/app/src/main/res/drawable/bg_white_stroke_gray300_radius_4dp_ripple.xml
  android/app/src/main/res/layout/activity_login.xml
Labels: 🤖 AN, 🎀 design

#209 feat: 당해 년도 직관 내역 최신순 조회에 팀 코드 추가
  backend/src/main/java/com/yagubogu/checkin/dto/CheckInGameTeamResponse.java
  backend/src/main/java/com/yagubogu/checkin/repository/CheckInRepository.java
  backend/src/test/java/com/yagubogu/checkin/service/CheckInServiceTest.java
Labels: 🚀 feat, 🐒 BE

#199 feat: 로그아웃 기능, 인가 구현
  backend/src/main/java/com/yagubogu/auth/annotation/RequireRole.java
  backend/src/main/java/com/yagubogu/auth/config/WebConfig.java
  backend/src/main/java/com/yagubogu/auth/controller/AuthController.java
  backend/src/main/java/com/yagubogu/auth/dto/LogoutRequest.java
  backend/src/main/java/com/yagubogu/auth/interceptor/AuthInterceptor.java
  backend/src/main/java/com/yagubogu/auth/service/AuthService.java
  backend/src/main/java/com/yagubogu/auth/support/AuthorizationExtractor.java
  backend/src/main/java/com/yagubogu/checkin/controller/CheckInController.java
  backend/src/main/java/com/yagubogu/checkin/dto/CreateCheckInRequest.java
  backend/src/main/java/com/yagubogu/checkin/service/CheckInService.java
  backend/src/main/java/com/yagubogu/member/controller/MemberController.java
  backend/src/main/java/com/yagubogu/member/domain/Role.java
  backend/src/main/java/com/yagubogu/stat/controller/StatController.java
  backend/src/main/java/com/yagubogu/talk/controller/TalkController.java
  backend/src/test/java/com/yagubogu/auth/AuthIntegrationTest.java
  backend/src/test/java/com/yagubogu/auth/service/AuthServiceTest.java
  backend/src/test/java/com/yagubogu/auth/support/AuthorizationExtractorTest.java
  backend/src/test/java/com/yagubogu/checkin/CheckInIntegrationTest.java
  backend/src/test/java/com/yagubogu/checkin/service/CheckInServiceTest.java
  backend/src/test/java/com/yagubogu/fixture/TestSupport.java
  backend/src/test/java/com/yagubogu/member/MemberIntegrationTest.java
  backend/src/test/java/com/yagubogu/stat/StatIntegrationTest.java
  backend/src/test/java/com/yagubogu/talk/TalkIntegrationTest.java
  backend/src/test/resources/test-data.sql
Labels: 🚀 feat, 🐒 BE

#216 feat: 오늘 경기하는 모든 구장, 팀, 인증 여부 조회 기능 구현
  backend/src/main/java/com/yagubogu/game/controller/GameController.java
  backend/src/main/java/com/yagubogu/game/dto/GameResponse.java
  backend/src/main/java/com/yagubogu/game/dto/GameWithCheckIn.java
  backend/src/main/java/com/yagubogu/game/dto/GamesResponse.java
  backend/src/main/java/com/yagubogu/game/dto/StadiumByGame.java
  backend/src/main/java/com/yagubogu/game/dto/TeamByGame.java
  backend/src/main/java/com/yagubogu/game/repository/GameRepository.java
  backend/src/main/java/com/yagubogu/game/service/GameService.java
  backend/src/main/java/com/yagubogu/talk/controller/TalkController.java
  backend/src/test/java/com/yagubogu/game/GameIntegrationTest.java
  backend/src/test/java/com/yagubogu/game/service/GameServiceTest.java
Labels: 🚀 feat, 🐒 BE

#215 feat: 응원팀 선택 또는 수정 기능 구현
  backend/src/main/java/com/yagubogu/member/controller/MemberController.java
  backend/src/main/java/com/yagubogu/member/domain/Member.java
  backend/src/main/java/com/yagubogu/member/dto/MemberFavoriteRequest.java
  backend/src/main/java/com/yagubogu/member/service/MemberService.java
  backend/src/test/java/com/yagubogu/member/MemberIntegrationTest.java
  backend/src/test/java/com/yagubogu/member/service/MemberServiceTest.java
  backend/src/test/resources/test-data.sql
Labels: 🚀 feat, 🐒 BE

#222 chore: 토큰 유효기간 변경
  backend/src/main/resources/application.yml
Labels: 🐒 BE, ⚙️ chore

#206 feat: 구장별 팬 점유율 API 연동
  android/app/src/main/java/com/yagubogu/data/datasource/CheckInsDataSource.kt
  android/app/src/main/java/com/yagubogu/data/datasource/CheckInsRemoteDataSource.kt
  android/app/src/main/java/com/yagubogu/data/datasource/StatsDataSource.kt
  android/app/src/main/java/com/yagubogu/data/datasource/StatsRemoteDataSource.kt
  android/app/src/main/java/com/yagubogu/data/dto/response/FanRateByGameDto.kt
  android/app/src/main/java/com/yagubogu/data/dto/response/FanRateResponse.kt
  android/app/src/main/java/com/yagubogu/data/dto/response/TeamFanRateDto.kt
  android/app/src/main/java/com/yagubogu/data/dto/response/TeamOccupancyRateDto.kt
  android/app/src/main/java/com/yagubogu/data/dto/response/TeamOccupancyRatesResponse.kt
  android/app/src/main/java/com/yagubogu/data/repository/CheckInsDefaultRepository.kt
  android/app/src/main/java/com/yagubogu/data/repository/StatsDefaultRepository.kt
  android/app/src/main/java/com/yagubogu/data/service/CheckInsApiService.kt
  android/app/src/main/java/com/yagubogu/data/service/StatsApiService.kt
  android/app/src/main/java/com/yagubogu/domain/model/Team.kt
  android/app/src/main/java/com/yagubogu/domain/repository/CheckInsRepository.kt
  android/app/src/main/java/com/yagubogu/domain/repository/StatsRepository.kt
  android/app/src/main/java/com/yagubogu/presentation/home/HomeFragment.kt
  android/app/src/main/java/com/yagubogu/presentation/home/HomeViewModel.kt
  android/app/src/main/java/com/yagubogu/presentation/home/model/StadiumFanRate.kt
  android/app/src/main/java/com/yagubogu/presentation/home/model/StadiumStatsUiModel.kt
  android/app/src/main/java/com/yagubogu/presentation/home/model/TeamFanRate.kt
  android/app/src/main/res/layout/fragment_home.xml
  android/app/src/main/res/layout/item_stadium_chart_bar.xml
  android/app/src/main/res/values/strings.xml
Labels: 🚀 feat, 🤖 AN

#224 feat: 토큰 유효기간 수정 및 리프레시 토큰 발급 권한 수정
  backend/src/main/java/com/yagubogu/auth/controller/AuthController.java
  backend/src/main/resources/application.yml
Labels: 🚀 feat, 🐒 BE

#230 fix: 충돌 해결
  backend/src/test/java/com/yagubogu/auth/AuthIntegrationTest.java
Labels: 🔨 fix, 🐒 BE

#231 Dev be -> Dev
  backend/src/main/java/com/yagubogu/auth/controller/AuthController.java
  backend/src/test/java/com/yagubogu/auth/AuthIntegrationTest.java
Labels: 🐒 BE

#240 feat: 게임 목록에 게임 id 추가
  backend/src/main/java/com/yagubogu/game/dto/GameWithCheckIn.java
  backend/src/main/java/com/yagubogu/game/repository/GameRepository.java
  backend/src/test/java/com/yagubogu/game/GameIntegrationTest.java
  backend/src/test/java/com/yagubogu/game/service/GameServiceTest.java
Labels: 🚀 feat, 🐒 BE

#252 feat: [BE] Logging 구현
  backend/src/main/java/com/yagubogu/game/schedule/GameScheduler.java
  backend/src/main/java/com/yagubogu/global/GlobalExceptionHandler.java
  backend/src/main/java/com/yagubogu/global/LoggingInterceptor.java
  backend/src/main/java/com/yagubogu/global/TransactionalLoggingAspect.java
  backend/src/main/resources/log4j2-spring.xml
Labels: 🚀 feat, 🐒 BE

#256 docs: Swagger 문서화
  backend/src/main/java/com/yagubogu/checkin/controller/CheckInController.java
  backend/src/main/java/com/yagubogu/checkin/controller/CheckInControllerInterface.java
  backend/src/main/java/com/yagubogu/game/controller/GameController.java
  backend/src/main/java/com/yagubogu/game/controller/GameControllerInterface.java
  backend/src/main/java/com/yagubogu/member/controller/MemberController.java
  backend/src/main/java/com/yagubogu/member/controller/MemberControllerInterface.java
  backend/src/main/java/com/yagubogu/stadium/controller/StadiumController.java
  backend/src/main/java/com/yagubogu/stadium/controller/StadiumControllerInterface.java
  backend/src/main/java/com/yagubogu/stat/controller/StatController.java
  backend/src/main/java/com/yagubogu/stat/controller/StatControllerInterface.java
  backend/src/main/java/com/yagubogu/talk/controller/TalkController.java
  backend/src/main/java/com/yagubogu/talk/controller/TalkControllerInterface.java
Labels: 📄 docs, 🐒 BE

#263 fix: 서버 예외 메세지 출력 오류 수정
  backend/src/main/java/com/yagubogu/auth/controller/AuthController.java
  backend/src/main/java/com/yagubogu/auth/controller/AuthControllerInterface.java
  backend/src/main/java/com/yagubogu/checkin/controller/CheckInControllerInterface.java
  backend/src/main/java/com/yagubogu/game/controller/GameControllerInterface.java
  backend/src/main/java/com/yagubogu/global/GlobalExceptionHandler.java
  backend/src/main/java/com/yagubogu/global/config/WebConfig.java
  backend/src/main/java/com/yagubogu/member/controller/MemberControllerInterface.java
  backend/src/main/java/com/yagubogu/stat/controller/StatControllerInterface.java
  backend/src/main/java/com/yagubogu/talk/controller/TalkControllerInterface.java
Labels: 🔨 fix, 🐒 BE

#247 feat: 평균 득, 실, 안타, 피안타, 실책 조회 API 연동
  android/app/src/main/java/com/yagubogu/data/datasource/StatsDataSource.kt
  android/app/src/main/java/com/yagubogu/data/datasource/StatsRemoteDataSource.kt
  android/app/src/main/java/com/yagubogu/data/dto/response/AverageStatisticResponse.kt
  android/app/src/main/java/com/yagubogu/data/repository/StatsDefaultRepository.kt
  android/app/src/main/java/com/yagubogu/data/service/StatsApiService.kt
  android/app/src/main/java/com/yagubogu/domain/repository/StatsRepository.kt
  android/app/src/main/java/com/yagubogu/presentation/stats/my/AverageStats.kt
  android/app/src/main/java/com/yagubogu/presentation/stats/my/MyStatsFragment.kt
  android/app/src/main/java/com/yagubogu/presentation/stats/my/MyStatsViewModel.kt
  android/app/src/main/res/layout/fragment_my_stats.xml
  android/app/src/main/res/values/strings.xml
Labels: 🚀 feat, 🤖 AN

#270 chore: 디스코드 PR 알림 workflow 체리픽
  .github/workflows/discord-notify.yml
Labels: 🤖 AN, ⚙️ chore

#275 feat: 내부 회원 api 구현
  .github/workflows/backend-dev-be.yml
  backend/src/main/java/com/yagubogu/auth/service/AuthService.java
  backend/src/main/java/com/yagubogu/internal/controller/InternalAuthController.java
  backend/src/main/java/com/yagubogu/internal/controller/InternalAuthControllerInterface.java
  backend/src/main/java/com/yagubogu/internal/service/InternalAuthService.java
  backend/src/main/resources/application-dev.yml
Labels: 🚀 feat, 🐒 BE

#281 chore: 로깅 형식 수정
  backend/src/main/resources/log4j2-spring.xml
Labels: 🚀 feat, 🐒 BE

#267 feat: 승리요정 랭킹 API 연동
  android/app/build.gradle.kts
  android/app/src/main/java/com/yagubogu/data/datasource/CheckInsDataSource.kt
  android/app/src/main/java/com/yagubogu/data/datasource/CheckInsRemoteDataSource.kt
  android/app/src/main/java/com/yagubogu/data/dto/response/VictoryFairyRankingDto.kt
  android/app/src/main/java/com/yagubogu/data/dto/response/VictoryFairyRankingResponse.kt
  android/app/src/main/java/com/yagubogu/data/repository/CheckInsDefaultRepository.kt
  android/app/src/main/java/com/yagubogu/data/service/CheckInsApiService.kt
  android/app/src/main/java/com/yagubogu/domain/repository/CheckInsRepository.kt
  android/app/src/main/java/com/yagubogu/presentation/home/HomeFragment.kt
  android/app/src/main/java/com/yagubogu/presentation/home/HomeViewModel.kt
  android/app/src/main/java/com/yagubogu/presentation/home/model/StadiumStatsUiModel.kt
  android/app/src/main/java/com/yagubogu/presentation/home/ranking/VictoryFairyItem.kt
  android/app/src/main/java/com/yagubogu/presentation/home/ranking/VictoryFairyRanking.kt
  android/app/src/main/java/com/yagubogu/presentation/livetalk/LivetalkViewModel.kt
  android/app/src/main/java/com/yagubogu/presentation/util/BindingAdapters.kt
  android/app/src/main/res/drawable/ic_user.xml
  android/app/src/main/res/layout/item_victory_fairy.xml
  android/app/src/main/res/values/strings.xml
Labels: 🚀 feat, 🤖 AN

#304 test: test.sql 제거 및 테스트 Fixture에 Builder 패턴 적용
  backend/src/test/java/com/yagubogu/auth/AuthIntegrationTest.java
  backend/src/test/java/com/yagubogu/auth/config/AuthTestConfig.java
  backend/src/test/java/com/yagubogu/checkin/CheckInIntegrationTest.java
  backend/src/test/java/com/yagubogu/game/GameIntegrationTest.java
  backend/src/test/java/com/yagubogu/member/MemberIntegrationTest.java
  backend/src/test/java/com/yagubogu/support/TestSupport.java
  backend/src/test/java/com/yagubogu/support/auth/AuthFactory.java
  backend/src/test/java/com/yagubogu/support/checkin/CheckInBuilder.java
  backend/src/test/java/com/yagubogu/support/checkin/CheckInFactory.java
  backend/src/test/java/com/yagubogu/support/game/GameBuilder.java
  backend/src/test/java/com/yagubogu/support/game/GameFactory.java
  backend/src/test/java/com/yagubogu/support/member/MemberFactory.java
  backend/src/test/java/com/yagubogu/support/talk/TalkBuilder.java
  backend/src/test/java/com/yagubogu/support/talk/TalkFactory.java
  backend/src/test/java/com/yagubogu/support/talk/TalkReportBuilder.java
  backend/src/test/java/com/yagubogu/support/talk/TalkReportFactory.java
Labels: 🐒 BE, 💯 test

#254 feat: 당해 년도 직관 내역 최신순 조회 API 연동
  android/app/src/main/java/com/yagubogu/data/datasource/CheckInsDataSource.kt
  android/app/src/main/java/com/yagubogu/data/datasource/CheckInsRemoteDataSource.kt
  android/app/src/main/java/com/yagubogu/data/dto/response/checkin/CheckInGameDto.kt
  android/app/src/main/java/com/yagubogu/data/dto/response/checkin/CheckInGameTeamDto.kt
  android/app/src/main/java/com/yagubogu/data/dto/response/checkin/CheckInHistoryResponse.kt
  android/app/src/main/java/com/yagubogu/data/repository/CheckInsDefaultRepository.kt
  android/app/src/main/java/com/yagubogu/data/service/CheckInsApiService.kt
  android/app/src/main/java/com/yagubogu/domain/repository/CheckInsRepository.kt
  android/app/src/main/java/com/yagubogu/presentation/livetalk/LivetalkViewModel.kt
  android/app/src/main/java/com/yagubogu/presentation/login/LoginActivity.kt
  android/app/src/main/java/com/yagubogu/presentation/stats/attendance/AttendanceHistoryFilter.kt
  android/app/src/main/java/com/yagubogu/presentation/stats/attendance/AttendanceHistoryFragment.kt
  android/app/src/main/java/com/yagubogu/presentation/stats/attendance/AttendanceHistoryItem.kt
  android/app/src/main/java/com/yagubogu/presentation/stats/attendance/AttendanceHistoryViewModel.kt
  android/app/src/main/java/com/yagubogu/presentation/stats/attendance/AttendanceHistoryViewModelFactory.kt
  android/app/src/main/java/com/yagubogu/presentation/stats/attendance/CheckInGameTeamItem.kt
  android/app/src/main/res/layout/fragment_attendance_history.xml
Labels: 🚀 feat, 🤖 AN

#312 test: Builder, Factory를 이용한 테스트 수정
  backend/src/main/java/com/yagubogu/checkin/repository/CheckInRepository.java
  backend/src/main/java/com/yagubogu/stat/service/StatService.java
  backend/src/test/java/com/yagubogu/auth/config/AuthTestConfig.java
  backend/src/test/java/com/yagubogu/stat/StatIntegrationTest.java
  backend/src/test/java/com/yagubogu/stat/service/StatServiceTest.java
  backend/src/test/resources/test-data-team-stadium.sql
Labels: 🐒 BE, 💯 test

#315 feat: Logging 고도화
  backend/src/main/java/com/yagubogu/global/LoggingInterceptor.java
  backend/src/main/java/com/yagubogu/global/TransactionalLoggingAspect.java
  backend/src/main/java/com/yagubogu/global/config/WebConfig.java
  backend/src/main/resources/log4j2-spring.xml
Labels: 🚀 feat, 🐒 BE

#317 test: Auth, Game 테스트 수정
  backend/src/test/java/com/yagubogu/auth/AuthIntegrationTest.java
  backend/src/test/java/com/yagubogu/auth/config/AuthTestConfig.java
  backend/src/test/java/com/yagubogu/auth/service/AuthServiceTest.java
  backend/src/test/java/com/yagubogu/auth/support/AuthGatewayTest.java
  backend/src/test/java/com/yagubogu/game/GameIntegrationTest.java
  backend/src/test/java/com/yagubogu/game/service/GameScheduleSyncServiceTest.java
  backend/src/test/java/com/yagubogu/game/service/GameServiceTest.java
  backend/src/test/java/com/yagubogu/support/refreshtoken/RefreshTokenBuilder.java
  backend/src/test/java/com/yagubogu/support/refreshtoken/RefreshTokenFactory.java
Labels: 🐒 BE, 💯 test

#318 test: talk and stadium 테스트 수정
  backend/src/test/java/com/yagubogu/stadium/StadiumIntegrationTest.java
  backend/src/test/java/com/yagubogu/stadium/service/StadiumServiceTest.java
  backend/src/test/java/com/yagubogu/talk/TalkIntegrationTest.java
  backend/src/test/java/com/yagubogu/talk/service/TalkReportServiceTest.java
  backend/src/test/java/com/yagubogu/talk/service/TalkServiceTest.java
  backend/src/test/resources/talk-test-data.sql
Labels: 🐒 BE, 💯 test

#325 fix: 응원팀 조회 시 team이 null일 때 null 반환하도록 수정
  backend/src/main/java/com/yagubogu/member/service/MemberService.java
Labels: 🚀 feat, 🐒 BE

#329 feat: 신규 톡 폴링 조회 순서 반대로 하기
  backend/src/main/java/com/yagubogu/talk/repository/TalkRepository.java
  backend/src/main/java/com/yagubogu/talk/service/TalkReportService.java
  backend/src/test/java/com/yagubogu/talk/service/TalkServiceTest.java
Labels: 🚀 feat, 🐒 BE

#342 fix: dockerfile 경로 수정
  .github/workflows/backend-dev.yml
Labels: 🐒 BE, ⚙️ chore

#343 fix: dockerfile 경로 수정
  .github/workflows/backend-dev.yml
Labels: 🐒 BE

#345 chore: 스크립트 공백 제거 및 빌드 단계 제거 (#344)
  .github/workflows/backend-dev.yml
Labels: 🐒 BE

#347 chore: jdk 변경 (#346)
  .github/workflows/backend-dev.yml
  backend/Dockerfile
Labels: 🐒 BE

#350 chore: health check 제거
  .github/workflows/backend-dev.yml
Labels: 🐒 BE, ⚙️ chore

#326 fix: 토큰 재발급 로직 개선
  android/app/src/main/java/com/yagubogu/data/network/TokenAuthenticator.kt
  android/app/src/main/java/com/yagubogu/data/util/RequestExt.kt
  android/app/src/main/java/com/yagubogu/presentation/stats/attendance/AttendanceHistoryFragment.kt
  android/app/src/main/java/com/yagubogu/presentation/stats/attendance/AttendanceHistoryViewModel.kt
Labels: 🔨 fix, 🤖 AN

#359 fix: 회원 탈퇴 후 재가입이 안되던 문제 해결
  backend/src/main/java/com/yagubogu/auth/domain/RefreshToken.java
  backend/src/main/java/com/yagubogu/member/domain/Member.java
Labels: 🐒 BE

#307 feat: 회원가입 시 응원팀 선택 기능 구현
  android/app/src/main/java/com/yagubogu/data/dto/response/MemberDto.kt
  android/app/src/main/java/com/yagubogu/data/dto/response/MemberFavoriteResponse.kt
  android/app/src/main/java/com/yagubogu/data/repository/AuthDefaultRepository.kt
  android/app/src/main/java/com/yagubogu/data/repository/MemberDefaultRepository.kt
  android/app/src/main/java/com/yagubogu/domain/model/LoginResult.kt
  android/app/src/main/java/com/yagubogu/domain/repository/AuthRepository.kt
  android/app/src/main/java/com/yagubogu/domain/repository/MemberRepository.kt
  android/app/src/main/java/com/yagubogu/presentation/favorite/FavoriteTeamActivity.kt
  android/app/src/main/java/com/yagubogu/presentation/favorite/FavoriteTeamAdapter.kt
  android/app/src/main/java/com/yagubogu/presentation/favorite/FavoriteTeamConfirmFragment.kt
  android/app/src/main/java/com/yagubogu/presentation/favorite/FavoriteTeamItem.kt
  android/app/src/main/java/com/yagubogu/presentation/favorite/FavoriteTeamViewHolder.kt
  android/app/src/main/java/com/yagubogu/presentation/favorite/FavoriteTeamViewModel.kt
  android/app/src/main/java/com/yagubogu/presentation/favorite/FavoriteTeamViewModelFactory.kt
  android/app/src/main/java/com/yagubogu/presentation/home/HomeViewModel.kt
  android/app/src/main/java/com/yagubogu/presentation/home/model/MemberStatsUiModel.kt
  android/app/src/main/java/com/yagubogu/presentation/login/LoginActivity.kt
  android/app/src/main/java/com/yagubogu/presentation/login/LoginViewModel.kt
  android/app/src/main/java/com/yagubogu/presentation/login/LoginViewModelFactory.kt
  android/app/src/main/java/com/yagubogu/presentation/stats/my/MyStatsUiModel.kt
  android/app/src/main/java/com/yagubogu/presentation/stats/my/MyStatsViewModel.kt
  android/app/src/main/res/layout/fragment_favorite_team_confirm.xml
  android/app/src/main/res/layout/item_favorite_team.xml
Labels: 🚀 feat, 🤖 AN

#369 design: 로그인 화면 배경 이미지 변경
  android/app/src/main/res/drawable/bg_login.png
  android/app/src/main/res/drawable/img_login.png
  android/app/src/main/res/layout/activity_login.xml
  android/app/src/main/res/values/strings.xml
Labels: 🤖 AN, 🎀 design

#367 design: 직관내역, 현장톡 "없어요..." 추가
  android/app/src/main/java/com/yagubogu/presentation/attendance/AttendanceHistoryFragment.kt
  android/app/src/main/java/com/yagubogu/presentation/livetalk/LivetalkFragment.kt
  android/app/src/main/res/drawable/img_baseball_fly_error.png
  android/app/src/main/res/drawable/img_baseball_scoreboard.png
  android/app/src/main/res/layout/fragment_attendance_history.xml
  android/app/src/main/res/layout/fragment_livetalk.xml
  android/app/src/main/res/values/strings.xml
Labels: 🤖 AN, 🎀 design

#360 chore: prod용 워크플로우 생성
  .github/workflows/backend-main.yml
  .github/workflows/backend-rollback-main.yml
  backend/Dockerfile
  backend/docker-compose.db.yml
  backend/src/main/java/com/yagubogu/YaguboguApplication.java
  backend/src/main/resources/application-prod.yml
  backend/src/main/resources/db/schema.sql
Labels: 🐒 BE, ⚙️ chore

#381 dev-be -> dev
  .github/workflows/backend-main.yml
  .github/workflows/backend-rollback-main.yml
  backend/Dockerfile
  backend/docker-compose.db.yml
  backend/src/main/java/com/yagubogu/YaguboguApplication.java
  backend/src/main/java/com/yagubogu/checkin/dto/FanRateGameEntry.java
  backend/src/main/java/com/yagubogu/checkin/dto/FanRateResponse.java
  backend/src/main/java/com/yagubogu/checkin/dto/GameWithFanCountsResponse.java
  backend/src/main/java/com/yagubogu/checkin/repository/CheckInRepository.java
  backend/src/main/java/com/yagubogu/checkin/service/CheckInService.java
  backend/src/main/resources/application-prod.yml
  backend/src/main/resources/db/schema.sql
  backend/src/test/java/com/yagubogu/checkin/service/CheckInServiceTest.java
Labels: 🐒 BE

#370 feat: 직관 내역 상세 UI 구현
  android/app/build.gradle.kts
  android/app/src/main/java/com/yagubogu/data/dto/response/checkin/CheckInGameDto.kt
  android/app/src/main/java/com/yagubogu/data/dto/response/checkin/CheckInGameTeamDto.kt
  android/app/src/main/java/com/yagubogu/data/repository/CheckInsDefaultRepository.kt
  android/app/src/main/java/com/yagubogu/domain/repository/CheckInsRepository.kt
  android/app/src/main/java/com/yagubogu/presentation/attendance/AttendanceHistoryAdapter.kt
  android/app/src/main/java/com/yagubogu/presentation/attendance/AttendanceHistoryDetailViewHolder.kt
  android/app/src/main/java/com/yagubogu/presentation/attendance/AttendanceHistoryFragment.kt
  android/app/src/main/java/com/yagubogu/presentation/attendance/AttendanceHistoryItem.kt
  android/app/src/main/java/com/yagubogu/presentation/attendance/AttendanceHistorySummaryViewHolder.kt
  android/app/src/main/java/com/yagubogu/presentation/attendance/AttendanceHistoryViewHolder.kt
  android/app/src/main/java/com/yagubogu/presentation/attendance/AttendanceHistoryViewModel.kt
  android/app/src/main/java/com/yagubogu/presentation/attendance/model/AttendanceHistoryFilter.kt
  android/app/src/main/java/com/yagubogu/presentation/attendance/model/AttendanceHistoryItem.kt
  android/app/src/main/java/com/yagubogu/presentation/attendance/model/AttendanceHistorySort.kt
  android/app/src/main/java/com/yagubogu/presentation/attendance/model/AttendanceHistoryTeamItem.kt
  android/app/src/main/java/com/yagubogu/presentation/favorite/FavoriteTeamViewHolder.kt
  android/app/src/main/java/com/yagubogu/presentation/home/ranking/VictoryFairyViewHolder.kt
  android/app/src/main/java/com/yagubogu/presentation/home/stadium/StadiumFanRateViewHolder.kt
  android/app/src/main/java/com/yagubogu/presentation/livetalk/chat/LivetalkMyBubbleViewHolder.kt
  android/app/src/main/java/com/yagubogu/presentation/livetalk/chat/LivetalkOtherBubbleViewHolder.kt
  android/app/src/main/java/com/yagubogu/presentation/livetalk/stadium/LivetalkStadiumViewHolder.kt
  android/app/src/main/res/drawable/ic_switch.xml
  android/app/src/main/res/layout/fragment_attendance_history.xml
  android/app/src/main/res/layout/fragment_home.xml
  android/app/src/main/res/layout/item_attendance_history_detail.xml
  android/app/src/main/res/layout/item_attendance_history_summary.xml
  android/app/src/main/res/layout/item_spinner_attendance_history.xml
  android/app/src/main/res/layout/layout_attendance_history.xml
  android/app/src/main/res/values/strings.xml
  android/app/src/main/res/values/styles.xml
Labels: 🚀 feat, 🤖 AN

#391 fix: 깃 태그 생성 버그 해결
  .github/workflows/backend-main.yml
Labels: 🔨 fix, 🐒 BE, 👩🏿‍🌾 semver:minor

#392 fix: 변수명 수정
  .github/workflows/backend-dev.yml
  .github/workflows/backend-main.yml
Labels: 🧟‍♀️ semver:major

#393 fix: 충돌 해결
  .github/workflows/backend-main.yml
Labels: 🔨 fix, 🐒 BE

#397 chore: dev workflow runs-on 아키텍처 수정, docker layer 캐시 추가
  .github/workflows/backend-dev.yml
Labels: 🐒 BE, ⚙️ chore

#398 chore: dev workflow runs-on 아키텍처 수정, docker layer 캐시 추가 (#397)
  .github/workflows/backend-dev.yml
Labels: 🐒 BE

#407 feat: 현장톡 삭제, 신고 API 연결_fix
  android/app/src/main/java/com/yagubogu/data/datasource/TalksDataSource.kt
  android/app/src/main/java/com/yagubogu/data/datasource/TalksRemoteDataSource.kt
  android/app/src/main/java/com/yagubogu/data/dto/response/talks/TalkDto.kt
  android/app/src/main/java/com/yagubogu/data/repository/TalksDefaultRepository.kt
  android/app/src/main/java/com/yagubogu/data/service/TalksApiService.kt
  android/app/src/main/java/com/yagubogu/data/util/ApiException.kt
  android/app/src/main/java/com/yagubogu/data/util/safeApiCall.kt
  android/app/src/main/java/com/yagubogu/domain/repository/TalksRepository.kt
  android/app/src/main/java/com/yagubogu/presentation/home/HomeFragment.kt
  android/app/src/main/java/com/yagubogu/presentation/livetalk/chat/LivetalkChatActivity.kt
  android/app/src/main/java/com/yagubogu/presentation/livetalk/chat/LivetalkChatAdapter.kt
  android/app/src/main/java/com/yagubogu/presentation/livetalk/chat/LivetalkChatEvent.kt
  android/app/src/main/java/com/yagubogu/presentation/livetalk/chat/LivetalkChatEventHandler.kt
  android/app/src/main/java/com/yagubogu/presentation/livetalk/chat/LivetalkChatItem.kt
  android/app/src/main/java/com/yagubogu/presentation/livetalk/chat/LivetalkChatViewModel.kt
  android/app/src/main/java/com/yagubogu/presentation/livetalk/chat/LivetalkMyBubbleViewHolder.kt
  android/app/src/main/java/com/yagubogu/presentation/livetalk/chat/LivetalkOtherBubbleViewHolder.kt
  android/app/src/main/java/com/yagubogu/presentation/livetalk/chat/model/LivetalkReportEvent.kt
  android/app/src/main/java/com/yagubogu/presentation/setting/SettingAccountFragment.kt
  android/app/src/main/java/com/yagubogu/presentation/setting/SettingDeleteAccountFragment.kt
  android/app/src/main/res/drawable/bg_primary050_radius_12dp_ripple.xml
  android/app/src/main/res/drawable/bg_white_radius_12dp_ripple.xml
  android/app/src/main/res/layout/fragment_setting_nickname_edit.xml
  android/app/src/main/res/layout/item_livetalk_my_bubble.xml
  android/app/src/main/res/layout/item_livetalk_other_bubble.xml
  android/app/src/main/res/values/strings.xml
Labels: 🚀 feat, 🤖 AN

#415 chore: dev, prod swagger baseurl 분리해서 설정
  backend/src/main/java/com/yagubogu/global/config/SwaggerConfig.java
  backend/src/main/java/com/yagubogu/global/config/SwaggerUiServersProperties.java
  backend/src/main/resources/application-dev.yml
  backend/src/main/resources/application-prod.yml
Labels: 🐒 BE, ⚙️ chore

#417 chore: dev, prod swagger baseurl 분리해서 설정
  .github/workflows/backend-dev.yml
  .github/workflows/backend-main.yml
  backend/src/main/java/com/yagubogu/global/config/SwaggerConfig.java
  backend/src/main/java/com/yagubogu/global/config/SwaggerUiServersProperties.java
  backend/src/main/resources/application-dev.yml
  backend/src/main/resources/application-prod.yml
Labels: 🐒 BE

#387 feat: 팀별 승률 조회 기능 구현
  backend/src/main/java/com/yagubogu/checkin/repository/CheckInRepository.java
  backend/src/main/java/com/yagubogu/global/config/SwaggerConfig.java
  backend/src/main/java/com/yagubogu/member/repository/MemberRepository.java
  backend/src/main/java/com/yagubogu/stat/controller/StatController.java
  backend/src/main/java/com/yagubogu/stat/controller/StatControllerInterface.java
  backend/src/main/java/com/yagubogu/stat/dto/OpponentWinRateResponse.java
  backend/src/main/java/com/yagubogu/stat/dto/OpponentWinRateRow.java
  backend/src/main/java/com/yagubogu/stat/dto/OpponentWinRateTeamResponse.java
  backend/src/main/java/com/yagubogu/stat/service/StatService.java
  backend/src/main/java/com/yagubogu/team/repository/TeamRepository.java
  backend/src/test/java/com/yagubogu/game/service/GameScheduleSyncServiceTest.java
  backend/src/test/java/com/yagubogu/member/service/MemberServiceTest.java
  backend/src/test/java/com/yagubogu/stat/StatIntegrationTest.java
  backend/src/test/java/com/yagubogu/stat/service/StatServiceTest.java
Labels: 🚀 feat, 🐒 BE

#376 feat: 경기 결과(직관 내역 페이지) 크롤링, 세부 경기 결과 조회 api 구현 #365
  backend/src/main/java/com/yagubogu/auth/dto/CreateTokenRequest.java
  backend/src/main/java/com/yagubogu/checkin/dto/CheckInGameResponse.java
  backend/src/main/java/com/yagubogu/checkin/dto/CheckInGameTeamResponse.java
  backend/src/main/java/com/yagubogu/checkin/dto/FanCountsByGameResponse.java
  backend/src/main/java/com/yagubogu/checkin/dto/TeamCheckInCountResponse.java
  backend/src/main/java/com/yagubogu/checkin/repository/CheckInRepository.java
  backend/src/main/java/com/yagubogu/game/domain/Game.java
  backend/src/main/java/com/yagubogu/game/domain/InningScoreConverter.java
  backend/src/main/java/com/yagubogu/game/domain/ScoreBoard.java
  backend/src/main/java/com/yagubogu/game/dto/GameResultResponse.java
  backend/src/main/java/com/yagubogu/game/dto/KboGameResultResponse.java
  backend/src/main/java/com/yagubogu/game/dto/Pitchers.java
  backend/src/main/java/com/yagubogu/game/service/GameResultSyncService.java
  backend/src/main/java/com/yagubogu/game/service/GameScheduleSyncService.java
  backend/src/main/java/com/yagubogu/game/service/GameService.java
  backend/src/main/java/com/yagubogu/game/service/client/KboGameResultClient.java
  backend/src/main/resources/data.sql
  backend/src/test/java/com/yagubogu/checkin/service/CheckInServiceTest.java
  backend/src/test/java/com/yagubogu/game/GameIntegrationTest.java
  backend/src/test/java/com/yagubogu/game/service/GameScheduleSyncServiceTest.java
  backend/src/test/java/com/yagubogu/game/service/GameServiceTest.java
  backend/src/test/java/com/yagubogu/stat/StatIntegrationTest.java
  backend/src/test/java/com/yagubogu/stat/service/StatServiceTest.java
  backend/src/test/java/com/yagubogu/support/TestFixture.java
  backend/src/test/java/com/yagubogu/support/game/GameBuilder.java
Labels: 🚀 feat, 🐒 BE

#423 design: 상세 통계 RecyclerView 스크롤 효과 제거
  android/app/src/main/java/com/yagubogu/presentation/stats/StatsFragment.kt
  android/app/src/main/java/com/yagubogu/presentation/stats/my/StatsMyFragment.kt
  android/app/src/main/java/com/yagubogu/presentation/stats/my/StatsMyUiModel.kt
  android/app/src/main/java/com/yagubogu/presentation/stats/my/StatsMyViewModel.kt
  android/app/src/main/java/com/yagubogu/presentation/stats/my/StatsMyViewModelFactory.kt
  android/app/src/main/res/layout/fragment_stats_detail.xml
  android/app/src/main/res/layout/fragment_stats_my.xml
Labels: 🤖 AN, 🎀 design

#426 Dev be -> Dev
  backend/src/main/java/com/yagubogu/auth/dto/CreateTokenRequest.java
  backend/src/main/java/com/yagubogu/checkin/controller/CheckInController.java
  backend/src/main/java/com/yagubogu/checkin/controller/CheckInControllerInterface.java
  backend/src/main/java/com/yagubogu/checkin/dto/CheckInGameResponse.java
  backend/src/main/java/com/yagubogu/checkin/dto/CheckInGameTeamResponse.java
  backend/src/main/java/com/yagubogu/checkin/dto/FanCountsByGameResponse.java
  backend/src/main/java/com/yagubogu/checkin/dto/StadiumCheckInCountResponse.java
  backend/src/main/java/com/yagubogu/checkin/dto/StadiumCheckInCountsResponse.java
  backend/src/main/java/com/yagubogu/checkin/dto/TeamCheckInCountResponse.java
  backend/src/main/java/com/yagubogu/checkin/repository/CheckInRepository.java
  backend/src/main/java/com/yagubogu/checkin/service/CheckInService.java
  backend/src/main/java/com/yagubogu/game/domain/Game.java
  backend/src/main/java/com/yagubogu/game/domain/InningScoreConverter.java
  backend/src/main/java/com/yagubogu/game/domain/ScoreBoard.java
  backend/src/main/java/com/yagubogu/game/dto/GameResultResponse.java
  backend/src/main/java/com/yagubogu/game/dto/KboGameResultResponse.java
  backend/src/main/java/com/yagubogu/game/dto/Pitchers.java
  backend/src/main/java/com/yagubogu/game/service/GameResultSyncService.java
  backend/src/main/java/com/yagubogu/game/service/GameScheduleSyncService.java
  backend/src/main/java/com/yagubogu/game/service/GameService.java
  backend/src/main/java/com/yagubogu/game/service/client/KboGameResultClient.java
  backend/src/main/java/com/yagubogu/global/config/JpaAuditingConfig.java
  backend/src/main/java/com/yagubogu/global/config/SwaggerConfig.java
  backend/src/main/java/com/yagubogu/member/controller/MemberController.java
  backend/src/main/java/com/yagubogu/member/controller/MemberControllerInterface.java
  backend/src/main/java/com/yagubogu/member/domain/Member.java
  backend/src/main/java/com/yagubogu/member/dto/MemberInfoResponse.java
  backend/src/main/java/com/yagubogu/member/repository/MemberRepository.java
  backend/src/main/java/com/yagubogu/member/service/MemberService.java
  backend/src/main/java/com/yagubogu/stat/controller/StatController.java
  backend/src/main/java/com/yagubogu/stat/controller/StatControllerInterface.java
  backend/src/main/java/com/yagubogu/stat/dto/OpponentWinRateResponse.java
  backend/src/main/java/com/yagubogu/stat/dto/OpponentWinRateRow.java
  backend/src/main/java/com/yagubogu/stat/dto/OpponentWinRateTeamResponse.java
  backend/src/main/java/com/yagubogu/stat/service/StatService.java
  backend/src/main/java/com/yagubogu/team/repository/TeamRepository.java
  backend/src/main/resources/data.sql
  backend/src/test/java/com/yagubogu/auth/AuthIntegrationTest.java
  backend/src/test/java/com/yagubogu/auth/service/AuthServiceTest.java
  backend/src/test/java/com/yagubogu/checkin/CheckInIntegrationTest.java
  backend/src/test/java/com/yagubogu/checkin/service/CheckInServiceTest.java
  backend/src/test/java/com/yagubogu/game/GameIntegrationTest.java
  backend/src/test/java/com/yagubogu/game/service/GameScheduleSyncServiceTest.java
  backend/src/test/java/com/yagubogu/game/service/GameServiceTest.java
  backend/src/test/java/com/yagubogu/member/MemberIntegrationTest.java
  backend/src/test/java/com/yagubogu/member/service/MemberServiceTest.java
  backend/src/test/java/com/yagubogu/stat/StatIntegrationTest.java
  backend/src/test/java/com/yagubogu/stat/service/StatServiceTest.java
  backend/src/test/java/com/yagubogu/support/TestFixture.java
  backend/src/test/java/com/yagubogu/support/game/GameBuilder.java
  backend/src/test/java/com/yagubogu/support/member/MemberBuilder.java
  backend/src/test/java/com/yagubogu/talk/TalkIntegrationTest.java
  backend/src/test/java/com/yagubogu/talk/service/TalkReportServiceTest.java
  backend/src/test/java/com/yagubogu/talk/service/TalkServiceTest.java
Labels: 🐒 BE

#445 fix: 로그아웃 시 캐시된 데이터 무효화
  android/app/src/main/java/com/yagubogu/data/repository/MemberDefaultRepository.kt
  android/app/src/main/java/com/yagubogu/domain/repository/MemberRepository.kt
  android/app/src/main/java/com/yagubogu/presentation/setting/SettingViewModel.kt
Labels: 🔨 fix, 🤖 AN

#451 fix: 직관 내역 조회 버그 수정
  backend/src/main/java/com/yagubogu/auth/support/GoogleAuthValidator.java
  backend/src/main/java/com/yagubogu/checkin/repository/CheckInRepository.java
  backend/src/test/java/com/yagubogu/checkin/service/CheckInServiceTest.java
  backend/src/test/java/com/yagubogu/support/TestFixture.java
Labels: 🔨 fix, 🐒 BE

#458 fix: 회원 탈퇴 시 DataStore에 저장된 데이터 삭제
  android/app/src/main/java/com/yagubogu/YaguBoguApplication.kt
  android/app/src/main/java/com/yagubogu/data/repository/MemberDefaultRepository.kt
Labels: 🔨 fix, 🤖 AN

#446 feat: 상세 통계 화면 API 연동
  android/app/src/main/java/com/yagubogu/data/datasource/checkin/CheckInDataSource.kt
  android/app/src/main/java/com/yagubogu/data/datasource/checkin/CheckInRemoteDataSource.kt
  android/app/src/main/java/com/yagubogu/data/datasource/stats/StatsDataSource.kt
  android/app/src/main/java/com/yagubogu/data/datasource/stats/StatsRemoteDataSource.kt
  android/app/src/main/java/com/yagubogu/data/dto/response/checkin/StadiumCheckInCountDto.kt
  android/app/src/main/java/com/yagubogu/data/dto/response/checkin/StadiumCheckInCountsResponse.kt
  android/app/src/main/java/com/yagubogu/data/dto/response/stats/OpponentWinRateResponse.kt
  android/app/src/main/java/com/yagubogu/data/dto/response/stats/OpponentWinRateTeamDto.kt
  android/app/src/main/java/com/yagubogu/data/repository/CheckInDefaultRepository.kt
  android/app/src/main/java/com/yagubogu/data/repository/StatsDefaultRepository.kt
  android/app/src/main/java/com/yagubogu/data/service/CheckInApiService.kt
  android/app/src/main/java/com/yagubogu/data/service/StatsApiService.kt
  android/app/src/main/java/com/yagubogu/domain/repository/CheckInRepository.kt
  android/app/src/main/java/com/yagubogu/domain/repository/StatsRepository.kt
  android/app/src/main/java/com/yagubogu/presentation/stats/detail/BarChartManager.kt
  android/app/src/main/java/com/yagubogu/presentation/stats/detail/StadiumVisitCount.kt
  android/app/src/main/java/com/yagubogu/presentation/stats/detail/StatsDetailFragment.kt
  android/app/src/main/java/com/yagubogu/presentation/stats/detail/StatsDetailViewModel.kt
  android/app/src/main/java/com/yagubogu/presentation/stats/detail/StatsDetailViewModelFactory.kt
Labels: 🚀 feat, 🤖 AN

#438 feat: 직관 내역 상세 API 연동
  android/app/src/main/java/com/yagubogu/data/datasource/checkin/CheckInDataSource.kt
  android/app/src/main/java/com/yagubogu/data/datasource/checkin/CheckInRemoteDataSource.kt
  android/app/src/main/java/com/yagubogu/data/dto/response/checkin/CheckInGameDto.kt
  android/app/src/main/java/com/yagubogu/data/dto/response/checkin/CheckInGameTeamDto.kt
  android/app/src/main/java/com/yagubogu/data/dto/response/checkin/ScoreBoardDto.kt
  android/app/src/main/java/com/yagubogu/data/repository/CheckInDefaultRepository.kt
  android/app/src/main/java/com/yagubogu/data/service/CheckInApiService.kt
  android/app/src/main/java/com/yagubogu/domain/repository/CheckInRepository.kt
  android/app/src/main/java/com/yagubogu/presentation/attendance/AttendanceHistoryDetailViewHolder.kt
  android/app/src/main/java/com/yagubogu/presentation/attendance/AttendanceHistoryFragment.kt
  android/app/src/main/java/com/yagubogu/presentation/attendance/AttendanceHistorySummaryViewHolder.kt
  android/app/src/main/java/com/yagubogu/presentation/attendance/AttendanceHistoryViewModel.kt
  android/app/src/main/java/com/yagubogu/presentation/attendance/model/AttendanceHistoryItem.kt
  android/app/src/main/java/com/yagubogu/presentation/attendance/model/AttendanceHistoryOrder.kt
  android/app/src/main/java/com/yagubogu/presentation/attendance/model/GameScoreBoard.kt
  android/app/src/main/java/com/yagubogu/presentation/attendance/model/GameTeam.kt
  android/app/src/main/res/layout/fragment_attendance_history.xml
  android/app/src/main/res/layout/item_attendance_history_detail.xml
  android/app/src/main/res/layout/item_attendance_history_summary.xml
  android/app/src/main/res/values/strings.xml
Labels: 🚀 feat, 🤖 AN

#463 feat: 회원 탈퇴시 refresh 토큰 만료 구현
  backend/src/main/java/com/yagubogu/auth/repository/RefreshTokenRepository.java
  backend/src/main/java/com/yagubogu/auth/service/AuthService.java
  backend/src/main/java/com/yagubogu/member/controller/MemberController.java
  backend/src/test/java/com/yagubogu/auth/service/AuthServiceTest.java
Labels: 🚀 feat, 🐒 BE

#461 releases 0.0.1
  backend/src/main/java/com/yagubogu/auth/repository/RefreshTokenRepository.java
  backend/src/main/java/com/yagubogu/auth/service/AuthService.java
  backend/src/main/java/com/yagubogu/member/controller/MemberController.java
  backend/src/main/resources/application-dev.yml
  backend/src/main/resources/db/migration/mysql/V1__init.sql
  backend/src/test/java/com/yagubogu/auth/service/AuthServiceTest.java
Labels: 🧑🏻‍🔧 semver:patch

#468 build: 야구보구 v1.0.0
  android/app/build.gradle.kts
Labels: 🤖 AN, 🔫 deploy
