Repository woowacourse-teams/2025-yagu-bogu, pull requests merged in 2025-07, with the labels that each got.

#6 docs: README.md 초기 설정
  .github/ISSUE_TEMPLATE/bug_report_issue_template.md
  .github/ISSUE_TEMPLATE/issue_create_template.md
  .github/PR_TEMPLATE/pull_request_template.md
  backend/README.md
Labels: 📄 docs

#7 feat: 안드로이드 프로젝트 초기 설정
  android/.gitignore
  android/app/.gitignore
  android/app/build.gradle.kts
  android/app/proguard-rules.pro
  android/app/src/androidTest/java/com/yagubogu/ExampleInstrumentedTest.kt
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/yagubogu/MainActivity.kt
  android/app/src/main/res/drawable/ic_launcher_background.xml
  android/app/src/main/res/drawable/ic_launcher_foreground.xml
  android/app/src/main/res/layout/activity_main.xml
  android/app/src/main/res/mipmap-anydpi/ic_launcher.xml
  android/app/src/main/res/mipmap-anydpi/ic_launcher_round.xml
  android/app/src/main/res/mipmap-hdpi/ic_launcher.webp
  android/app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  android/app/src/main/res/mipmap-mdpi/ic_launcher.webp
  android/app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  android/app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  android/app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  android/app/src/main/res/values-night/themes.xml
  android/app/src/main/res/values/colors.xml
  android/app/src/main/res/values/strings.xml
  android/app/src/main/res/values/themes.xml
  android/app/src/main/res/xml/backup_rules.xml
  android/app/src/main/res/xml/data_extraction_rules.xml
  android/app/src/test/java/com/yagubogu/ExampleUnitTest.kt
  android/build.gradle.kts
  android/gradle.properties
  android/gradle/libs.versions.toml
  android/gradle/wrapper/gradle-wrapper.jar
  android/gradle/wrapper/gradle-wrapper.properties
  android/gradlew
  android/gradlew.bat
  android/settings.gradle.kts
Labels: 🚀 feat, 🤖 AN

#10 docs: Android CI workflow_dispatch 적용
  .github/workflows/android-ci.yml
Labels: 📄 docs, 🤖 AN

#14 feat: BottomNavigation 구현
  android/app/build.gradle.kts
  android/app/src/main/java/com/yagubogu/MainActivity.kt
  android/app/src/main/java/com/yagubogu/presentation/challenge/ChallengeFragment.kt
  android/app/src/main/java/com/yagubogu/presentation/home/HomeFragment.kt
  android/app/src/main/java/com/yagubogu/presentation/record/RecordFragment.kt
  android/app/src/main/java/com/yagubogu/presentation/stats/StatsFragment.kt
  android/app/src/main/res/color/color_bottom_navigation.xml
  android/app/src/main/res/drawable/ic_challenge.xml
  android/app/src/main/res/drawable/ic_home.xml
  android/app/src/main/res/drawable/ic_record.xml
  android/app/src/main/res/drawable/ic_stats.xml
  android/app/src/main/res/layout/activity_main.xml
  android/app/src/main/res/layout/fragment_challenge.xml
  android/app/src/main/res/layout/fragment_home.xml
  android/app/src/main/res/layout/fragment_record.xml
  android/app/src/main/res/layout/fragment_stats.xml
  android/app/src/main/res/menu/menu_bottom_navigation.xml
  android/app/src/main/res/values/strings.xml
  android/app/src/main/res/values/styles.xml
  android/gradle/libs.versions.toml
Labels: 🚀 feat, 🤖 AN

#28 chore: ci cd workflow 설정
  .github/workflows/backend-ci.yml
  .github/workflows/backend-dev-be.yml
  .github/workflows/backend-dev.yml
  .gitignore
  backend/build.gradle
  backend/gradle/wrapper/gradle-wrapper.jar
  backend/gradle/wrapper/gradle-wrapper.properties
  backend/gradlew
  backend/gradlew.bat
  backend/settings.gradle
  backend/src/main/java/com/yagubogu/YaguboguApplication.java
  backend/src/main/resources/application.yml
  backend/src/main/resources/yaml/application-local.yml
  backend/src/main/resources/yaml/application-prod.yml
  backend/src/test/java/com/yagubogu/YaguboguApplicationTests.java
  backend/src/test/resources/application-test.yml
Labels: 🍃 BE, ⚙️ chore

#41 feat: Swagger 도입
  backend/build.gradle
  backend/src/main/java/com/yagubogu/global/config/SwaggerConfig.java
  backend/src/main/resources/application.yml
Labels: 🚀 feat, 🍃 BE

#26 feat: 홈 화면 UI 구현
  android/app/src/main/java/com/yagubogu/MainActivity.kt
  android/app/src/main/java/com/yagubogu/presentation/home/HomeFragment.kt
  android/app/src/main/res/drawable/bg_white_stroke_primary100_radius_12dp.xml
  android/app/src/main/res/drawable/ic_marker_pin.xml
  android/app/src/main/res/drawable/ic_settings.xml
  android/app/src/main/res/layout/activity_main.xml
  android/app/src/main/res/layout/fragment_home.xml
  android/app/src/main/res/menu/menu_home.xml
  android/app/src/main/res/values/strings.xml
  android/app/src/main/res/values/styles.xml
  android/app/src/main/res/values/themes.xml
Labels: 🚀 feat, 🤖 AN

#25 feat: 통계 TabLayout 구현
  android/app/src/main/java/com/yagubogu/presentation/stats/StatsFragment.kt
  android/app/src/main/java/com/yagubogu/presentation/stats/StatsTab.kt
  android/app/src/main/java/com/yagubogu/presentation/stats/my/MyStatsFragment.kt
  android/app/src/main/java/com/yagubogu/presentation/stats/stadium/StadiumListFragment.kt
  android/app/src/main/java/com/yagubogu/presentation/stats/stadium/StadiumStatsFragment.kt
  android/app/src/main/res/drawable/bg_primary050_stroke_primary100_radius_12dp.xml
  android/app/src/main/res/drawable/bg_primary500_radius_12dp.xml
  android/app/src/main/res/layout/fragment_my_stats.xml
  android/app/src/main/res/layout/fragment_stadium_list.xml
  android/app/src/main/res/layout/fragment_stadium_stats.xml
  android/app/src/main/res/layout/fragment_stats.xml
  android/app/src/main/res/layout/view_tab_stats.xml
  android/app/src/main/res/values/strings.xml
  android/app/src/main/res/values/styles.xml
Labels: 🚀 feat, 🤖 AN

#46 feat: 통계 Fragment ViewPager2 구현
  android/app/build.gradle.kts
  android/app/src/main/java/com/yagubogu/presentation/stats/StatsFragment.kt
  android/app/src/main/java/com/yagubogu/presentation/stats/StatsFragmentStateAdapter.kt
  android/app/src/main/res/layout/fragment_stats.xml
  android/gradle/libs.versions.toml
Labels: 🚀 feat, 🤖 AN

#57 feat: 내 팀 직관 승/패/무/총 횟수 API 구현
  backend/build.gradle
  backend/src/main/java/com/yagubogu/YaguboguApplication.java
  backend/src/main/java/com/yagubogu/attendance/domain/Attendance.java
  backend/src/main/java/com/yagubogu/checkin/domain/CheckIn.java
  backend/src/main/java/com/yagubogu/checkin/repository/CheckInRepository.java
  backend/src/main/java/com/yagubogu/checkin/service/CheckInService.java
  backend/src/main/java/com/yagubogu/game/domain/Game.java
  backend/src/main/java/com/yagubogu/global/exception/ForbiddenException.java
  backend/src/main/java/com/yagubogu/global/exception/NotFoundException.java
  backend/src/main/java/com/yagubogu/global/exception/YaguBoguException.java
  backend/src/main/java/com/yagubogu/member/domain/Member.java
  backend/src/main/java/com/yagubogu/member/domain/Role.java
  backend/src/main/java/com/yagubogu/member/repository/MemberRepository.java
  backend/src/main/java/com/yagubogu/stadium/domain/Stadium.java
  backend/src/main/java/com/yagubogu/stadium/repository/StadiumRepository.java
  backend/src/main/java/com/yagubogu/stat/controller/StatController.java
  backend/src/main/java/com/yagubogu/stat/dto/StatCountsResponse.java
  backend/src/main/java/com/yagubogu/stat/service/StatService.java
  backend/src/main/java/com/yagubogu/team/domain/Team.java
  backend/src/main/java/com/yagubogu/team/repository/TeamRepository.java
  backend/src/test/java/com/yagubogu/YaguboguApplicationTests.java
  backend/src/test/java/com/yagubogu/game/repository/GameRepository.java
  backend/src/test/java/com/yagubogu/member/domain/MemberTest.java
  backend/src/test/java/com/yagubogu/stat/StatIntegrationTest.java
  backend/src/test/java/com/yagubogu/stat/service/StatServiceTest.java
  backend/src/test/resources/application-test.yml
  backend/src/test/resources/application.yml
  backend/src/test/resources/test-data.sql
Labels: 🚀 feat, 🍃 BE

#62 chore: dev 프로필 추가
  .github/workflows/backend-dev.yml
  backend/src/main/resources/application.yml
  backend/src/main/resources/yaml/application-dev.yml
Labels: 🍃 BE, D-0, ⚙️ chore

#63 chore: dev 프로필 추가
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
  .github/workflows/backend-dev.yml
  backend/src/main/resources/application.yml
  backend/src/main/resources/yaml/application-dev.yml
Labels: 🍃 BE, D-0, ⚙️ chore

#56 feat: 직관 인증하기 로직 구현
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/yagubogu/YaguBoguApplication.kt
  android/app/src/main/java/com/yagubogu/data/datasource/LocationLocalDataSource.kt
  android/app/src/main/java/com/yagubogu/data/repository/LocationDefaultRepository.kt
  android/app/src/main/java/com/yagubogu/domain/model/Coordinate.kt
  android/app/src/main/java/com/yagubogu/domain/model/Distance.kt
  android/app/src/main/java/com/yagubogu/domain/model/Latitude.kt
  android/app/src/main/java/com/yagubogu/domain/model/Longitude.kt
  android/app/src/main/java/com/yagubogu/domain/model/Stadium.kt
  android/app/src/main/java/com/yagubogu/domain/repository/LocationRepository.kt
  android/app/src/main/java/com/yagubogu/presentation/MainActivity.kt
  android/app/src/main/java/com/yagubogu/presentation/home/HomeFragment.kt
  android/app/src/main/java/com/yagubogu/presentation/home/HomeViewModel.kt
  android/app/src/main/java/com/yagubogu/presentation/home/HomeViewModelFactory.kt
  android/app/src/main/java/com/yagubogu/presentation/home/LocationProvider.kt
  android/app/src/main/java/com/yagubogu/presentation/home/model/CheckInUiEvent.kt
  android/app/src/main/java/com/yagubogu/presentation/util/livedata/Event.kt
  android/app/src/main/java/com/yagubogu/presentation/util/livedata/MutableSingleLiveData.kt
  android/app/src/main/java/com/yagubogu/presentation/util/livedata/SingleLiveData.kt
  android/app/src/main/res/layout/activity_main.xml
  android/app/src/main/res/values/strings.xml
Labels: 🚀 feat, 🤖 AN

#66 feat: 오늘 구장의 팀별 점유율 조회
  backend/src/main/java/com/yagubogu/checkin/dto/TeamCheckInCountResponse.java
  backend/src/main/java/com/yagubogu/checkin/repository/CheckInRepository.java
  backend/src/main/java/com/yagubogu/member/repository/MemberRepository.java
  backend/src/main/java/com/yagubogu/stadium/controller/StadiumController.java
  backend/src/main/java/com/yagubogu/stadium/dto/TeamOccupancyRatesResponse.java
  backend/src/main/java/com/yagubogu/stadium/service/StadiumService.java
  backend/src/main/java/com/yagubogu/stat/dto/OccupancyRateTotalResponse.java
  backend/src/test/java/com/yagubogu/checkin/service/CheckInServiceTest.java
  backend/src/test/java/com/yagubogu/fixture/TestFixture.java
  backend/src/test/java/com/yagubogu/stadium/StadiumIntegrationTest.java
  backend/src/test/java/com/yagubogu/stadium/service/StadiumServiceTest.java
  backend/src/test/java/com/yagubogu/stat/StatIntegrationTest.java
  backend/src/test/java/com/yagubogu/stat/service/StatServiceTest.java
  backend/src/test/resources/test-data.sql
Labels: 🚀 feat, 🍃 BE

#71 feat: Retrofit 기본 설정
  android/app/build.gradle.kts
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/java/com/yagubogu/data/dto/response/StatsCountsResponse.kt
  android/app/src/main/java/com/yagubogu/data/network/RetrofitInstance.kt
  android/app/src/main/java/com/yagubogu/data/service/StatsApiService.kt
  android/app/src/main/res/xml/network_security_config.xml
  android/gradle/libs.versions.toml
Labels: 🚀 feat, 🤖 AN

#87 chore: mock 데이터 추가 및 stadium snake_case 적용, 점유율 포맷 고정
  backend/src/main/java/com/yagubogu/stadium/domain/Stadium.java
  backend/src/main/resources/data.sql
  backend/src/main/resources/yaml/application-dev.yml
  backend/src/main/resources/yaml/application-local.yml
Labels: 🐒 BE, ⚙️ chore

#88 feat: 응원팀 조회 기능 구현
  backend/src/main/java/com/yagubogu/member/controller/MemberController.java
  backend/src/main/java/com/yagubogu/member/dto/MemberFavoriteResponse.java
  backend/src/main/java/com/yagubogu/member/service/MemberService.java
  backend/src/test/java/com/yagubogu/member/MemberIntegrationTest.java
  backend/src/test/java/com/yagubogu/member/service/MemberServiceTest.java
  backend/src/test/java/com/yagubogu/stadium/StadiumIntegrationTest.java
  backend/src/test/java/com/yagubogu/stat/StatIntegrationTest.java
Labels: 🚀 feat, 🐒 BE, D-0

#86 feat: ExceptionHandler 구현, 구장별 팬 점유율 내림차순 수정
  backend/src/main/java/com/yagubogu/checkin/repository/CheckInRepository.java
  backend/src/main/java/com/yagubogu/global/GlobalExceptionHandler.java
  backend/src/main/java/com/yagubogu/global/exception/dto/ExceptionResponse.java
  backend/src/test/java/com/yagubogu/checkin/CheckInIntegrationTest.java
  backend/src/test/java/com/yagubogu/stadium/service/StadiumServiceTest.java
  backend/src/test/java/com/yagubogu/stat/StatIntegrationTest.java
Labels: 🚀 feat, 🐒 BE

#89 feat: 내 통계 화면 API 연동
  android/app/src/main/java/com/yagubogu/YaguBoguApplication.kt
  android/app/src/main/java/com/yagubogu/data/datasource/StatsDataSource.kt
  android/app/src/main/java/com/yagubogu/data/datasource/StatsRemoteDataSource.kt
  android/app/src/main/java/com/yagubogu/data/dto/response/StatsCountsResponse.kt
  android/app/src/main/java/com/yagubogu/data/dto/response/StatsLuckyStadiumsResponse.kt
  android/app/src/main/java/com/yagubogu/data/dto/response/StatsWinRateResponse.kt
  android/app/src/main/java/com/yagubogu/data/repository/StatsDefaultRepository.kt
  android/app/src/main/java/com/yagubogu/data/service/StatsApiService.kt
  android/app/src/main/java/com/yagubogu/data/util/safeApiCall.kt
  android/app/src/main/java/com/yagubogu/domain/model/StatsCounts.kt
  android/app/src/main/java/com/yagubogu/domain/repository/StatsRepository.kt
  android/app/src/main/java/com/yagubogu/presentation/stats/my/MyStatsFragment.kt
  android/app/src/main/java/com/yagubogu/presentation/stats/my/MyStatsUiModel.kt
  android/app/src/main/java/com/yagubogu/presentation/stats/my/MyStatsViewModel.kt
  android/app/src/main/java/com/yagubogu/presentation/stats/my/MyStatsViewModelFactory.kt
  android/app/src/main/res/layout/fragment_my_stats.xml
  android/app/src/main/res/values/strings.xml
  android/app/src/main/res/values/styles.xml
Labels: 🚀 feat, 🤖 AN

#84 feat: 총 인증 횟수 조회 API 구현
  backend/src/main/java/com/yagubogu/checkin/controller/CheckInController.java
  backend/src/main/java/com/yagubogu/checkin/dto/CheckInCountsResponse.java
  backend/src/main/java/com/yagubogu/checkin/repository/CheckInRepository.java
  backend/src/main/java/com/yagubogu/checkin/service/CheckInService.java
  backend/src/test/java/com/yagubogu/checkin/CheckInIntegrationTest.java
  backend/src/test/java/com/yagubogu/checkin/service/CheckInServiceTest.java
Labels: 🚀 feat, 🐒 BE

#96 chore: mock 데이터 수정
  backend/src/main/resources/data.sql
Labels: 🐒 BE, ⚙️ chore

#101 chore: springdoc 버전 2.7.0으로 수정
  backend/build.gradle
Labels: 🐒 BE, D-0, ⚙️ chore

#104 feat: 응원팀 조회 기능, 구장별 팬 점유율 조회 기능 구현
  backend/src/main/java/com/yagubogu/checkin/repository/CheckInRepository.java
  backend/src/main/java/com/yagubogu/member/dto/MemberFavoriteResponse.java
  backend/src/main/java/com/yagubogu/team/domain/Team.java
  backend/src/main/resources/data.sql
  backend/src/test/java/com/yagubogu/member/domain/MemberTest.java
  backend/src/test/resources/test-data.sql
Labels: 🚀 feat, 🐒 BE, D-0

#107 feat: 구장별 팬 점유율 조회 시 응답 데이터 추가
  backend/src/main/java/com/yagubogu/stadium/dto/TeamOccupancyRatesResponse.java
  backend/src/main/java/com/yagubogu/stadium/service/StadiumService.java
  backend/src/test/java/com/yagubogu/stadium/StadiumIntegrationTest.java
Labels: 🚀 feat, 🐒 BE

#112 chore: Discord PR 알림 기능 추가
  .github/workflows/discord-notify.yml
Labels: ⚙️ chore

#102 feat: 오늘의 구장 통계 화면 API 연동
  android/app/src/main/java/com/yagubogu/data/datasource/StatsDataSource.kt
  android/app/src/main/java/com/yagubogu/data/datasource/StatsRemoteDataSource.kt
  android/app/src/main/java/com/yagubogu/data/dto/response/TeamOccupancyRateDto.kt
  android/app/src/main/java/com/yagubogu/data/dto/response/TeamOccupancyRatesResponse.kt
  android/app/src/main/java/com/yagubogu/data/repository/StatsDefaultRepository.kt
  android/app/src/main/java/com/yagubogu/data/service/StatsApiService.kt
  android/app/src/main/java/com/yagubogu/domain/model/Team.kt
  android/app/src/main/java/com/yagubogu/domain/repository/StatsRepository.kt
  android/app/src/main/java/com/yagubogu/presentation/home/model/Stadium.kt
  android/app/src/main/java/com/yagubogu/presentation/stats/StatsFragment.kt
  android/app/src/main/java/com/yagubogu/presentation/stats/my/MyStatsViewModel.kt
  android/app/src/main/java/com/yagubogu/presentation/stats/stadium/StadiumListFragment.kt
  android/app/src/main/java/com/yagubogu/presentation/stats/stadium/StadiumStatsFragment.kt
  android/app/src/main/java/com/yagubogu/presentation/stats/stadium/StadiumStatsUiModel.kt
  android/app/src/main/java/com/yagubogu/presentation/stats/stadium/StadiumStatsViewModel.kt
  android/app/src/main/java/com/yagubogu/presentation/stats/stadium/StadiumStatsViewModelFactory.kt
  android/app/src/main/java/com/yagubogu/presentation/stats/stadium/TeamOccupancyStatus.kt
  android/app/src/main/java/com/yagubogu/presentation/stats/stadium/model/StadiumStatsUiModel.kt
  android/app/src/main/java/com/yagubogu/presentation/stats/stadium/model/TeamOccupancyRate.kt
  android/app/src/main/java/com/yagubogu/presentation/stats/stadium/model/TeamOccupancyRates.kt
  android/app/src/main/java/com/yagubogu/presentation/stats/stadium/model/TeamOccupancyStatus.kt
  android/app/src/main/java/com/yagubogu/presentation/util/TeamExt.kt
  android/app/src/main/res/layout/fragment_stadium_list.xml
  android/app/src/main/res/layout/fragment_stadium_stats.xml
  android/app/src/main/res/values/strings.xml
Labels: 🚀 feat, 🤖 AN

#117 [BE] pr, 이슈 관련 github actions workflow 추가
  .github/workflows/issue-close.yml
  .github/workflows/issue-setup.yml
  .github/workflows/pr-setup.yml
Labels: 🐒 BE, ⚙️ chore

#123 chore: yaml 디렉터리 제거 및 설정 파일 위치 정리
  backend/src/main/resources/application-dev.yml
  backend/src/main/resources/application-local.yml
  backend/src/main/resources/application-prod.yml
  backend/src/main/resources/application.yml
Labels: 🐒 BE, ⚙️ chore

#130 feat: 인증한 직관 내역을 최신순으로 조회하는 기능 구현
  backend/src/main/java/com/yagubogu/checkin/controller/CheckInController.java
  backend/src/main/java/com/yagubogu/checkin/dto/CheckInGameResponse.java
  backend/src/main/java/com/yagubogu/checkin/dto/CheckInGameTeamResponse.java
  backend/src/main/java/com/yagubogu/checkin/dto/CheckInHistoryResponse.java
  backend/src/main/java/com/yagubogu/checkin/repository/CheckInRepository.java
  backend/src/main/java/com/yagubogu/checkin/service/CheckInService.java
  backend/src/test/java/com/yagubogu/checkin/CheckInIntegrationTest.java
  backend/src/test/java/com/yagubogu/checkin/service/CheckInServiceTest.java
Labels: 🚀 feat, 🐒 BE

#133 design: 구장별 인증 통계에 막대 차트 디자인 적용
  android/app/src/main/java/com/yagubogu/presentation/stats/stadium/StadiumStatsFragment.kt
  android/app/src/main/java/com/yagubogu/presentation/stats/stadium/StadiumStatsViewModel.kt
  android/app/src/main/java/com/yagubogu/presentation/stats/stadium/model/StadiumStatsUiModel.kt
  android/app/src/main/java/com/yagubogu/presentation/util/BindingAdapters.kt
  android/app/src/main/res/drawable/bg_white_radius_100dp.xml
  android/app/src/main/res/drawable/img_chart_divider_trapezoid_left.xml
  android/app/src/main/res/drawable/img_chart_divider_trapezoid_right.xml
  android/app/src/main/res/layout/fragment_stadium_stats.xml
  android/app/src/main/res/layout/item_stadium_chart_bar.xml
  android/app/src/main/res/values/strings.xml
  android/app/src/main/res/values/styles.xml
Labels: 🤖 AN, 🎀 design
